// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_tables.proto

package ir.ms.pb;

/**
 * Protobuf type {@code PB_Comment}
 */
public  final class PB_Comment extends
    com.google.protobuf.GeneratedMessageLite<
        PB_Comment, PB_Comment.Builder> implements
    // @@protoc_insertion_point(message_implements:PB_Comment)
    PB_CommentOrBuilder {
  private PB_Comment() {
    text_ = "";
  }
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 Id = 1;</code>
   */
  public int getId() {
    return id_;
  }
  /**
   * <code>int32 Id = 1;</code>
   */
  private void setId(int value) {
    
    id_ = value;
  }
  /**
   * <code>int32 Id = 1;</code>
   */
  private void clearId() {
    
    id_ = 0;
  }

  public static final int USERID_FIELD_NUMBER = 3;
  private int userId_;
  /**
   * <code>int32 UserId = 3;</code>
   */
  public int getUserId() {
    return userId_;
  }
  /**
   * <code>int32 UserId = 3;</code>
   */
  private void setUserId(int value) {
    
    userId_ = value;
  }
  /**
   * <code>int32 UserId = 3;</code>
   */
  private void clearUserId() {
    
    userId_ = 0;
  }

  public static final int POSTID_FIELD_NUMBER = 5;
  private int postId_;
  /**
   * <code>int32 PostId = 5;</code>
   */
  public int getPostId() {
    return postId_;
  }
  /**
   * <code>int32 PostId = 5;</code>
   */
  private void setPostId(int value) {
    
    postId_ = value;
  }
  /**
   * <code>int32 PostId = 5;</code>
   */
  private void clearPostId() {
    
    postId_ = 0;
  }

  public static final int TEXT_FIELD_NUMBER = 7;
  private java.lang.String text_;
  /**
   * <code>string Text = 7;</code>
   */
  public java.lang.String getText() {
    return text_;
  }
  /**
   * <code>string Text = 7;</code>
   */
  public com.google.protobuf.ByteString
      getTextBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(text_);
  }
  /**
   * <code>string Text = 7;</code>
   */
  private void setText(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    text_ = value;
  }
  /**
   * <code>string Text = 7;</code>
   */
  private void clearText() {
    
    text_ = getDefaultInstance().getText();
  }
  /**
   * <code>string Text = 7;</code>
   */
  private void setTextBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    text_ = value.toStringUtf8();
  }

  public static final int CREATEDTIME_FIELD_NUMBER = 9;
  private int createdTime_;
  /**
   * <code>int32 CreatedTime = 9;</code>
   */
  public int getCreatedTime() {
    return createdTime_;
  }
  /**
   * <code>int32 CreatedTime = 9;</code>
   */
  private void setCreatedTime(int value) {
    
    createdTime_ = value;
  }
  /**
   * <code>int32 CreatedTime = 9;</code>
   */
  private void clearCreatedTime() {
    
    createdTime_ = 0;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (userId_ != 0) {
      output.writeInt32(3, userId_);
    }
    if (postId_ != 0) {
      output.writeInt32(5, postId_);
    }
    if (!text_.isEmpty()) {
      output.writeString(7, getText());
    }
    if (createdTime_ != 0) {
      output.writeInt32(9, createdTime_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (userId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, userId_);
    }
    if (postId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, postId_);
    }
    if (!text_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(7, getText());
    }
    if (createdTime_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, createdTime_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static ir.ms.pb.PB_Comment parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ir.ms.pb.PB_Comment parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ir.ms.pb.PB_Comment parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ir.ms.pb.PB_Comment parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ir.ms.pb.PB_Comment parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ir.ms.pb.PB_Comment parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ir.ms.pb.PB_Comment parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static ir.ms.pb.PB_Comment parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ir.ms.pb.PB_Comment parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ir.ms.pb.PB_Comment parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ir.ms.pb.PB_Comment prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code PB_Comment}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        ir.ms.pb.PB_Comment, Builder> implements
      // @@protoc_insertion_point(builder_implements:PB_Comment)
      ir.ms.pb.PB_CommentOrBuilder {
    // Construct using ir.ms.pb.PB_Comment.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int32 Id = 1;</code>
     */
    public int getId() {
      return instance.getId();
    }
    /**
     * <code>int32 Id = 1;</code>
     */
    public Builder setId(int value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>int32 Id = 1;</code>
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }

    /**
     * <code>int32 UserId = 3;</code>
     */
    public int getUserId() {
      return instance.getUserId();
    }
    /**
     * <code>int32 UserId = 3;</code>
     */
    public Builder setUserId(int value) {
      copyOnWrite();
      instance.setUserId(value);
      return this;
    }
    /**
     * <code>int32 UserId = 3;</code>
     */
    public Builder clearUserId() {
      copyOnWrite();
      instance.clearUserId();
      return this;
    }

    /**
     * <code>int32 PostId = 5;</code>
     */
    public int getPostId() {
      return instance.getPostId();
    }
    /**
     * <code>int32 PostId = 5;</code>
     */
    public Builder setPostId(int value) {
      copyOnWrite();
      instance.setPostId(value);
      return this;
    }
    /**
     * <code>int32 PostId = 5;</code>
     */
    public Builder clearPostId() {
      copyOnWrite();
      instance.clearPostId();
      return this;
    }

    /**
     * <code>string Text = 7;</code>
     */
    public java.lang.String getText() {
      return instance.getText();
    }
    /**
     * <code>string Text = 7;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      return instance.getTextBytes();
    }
    /**
     * <code>string Text = 7;</code>
     */
    public Builder setText(
        java.lang.String value) {
      copyOnWrite();
      instance.setText(value);
      return this;
    }
    /**
     * <code>string Text = 7;</code>
     */
    public Builder clearText() {
      copyOnWrite();
      instance.clearText();
      return this;
    }
    /**
     * <code>string Text = 7;</code>
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTextBytes(value);
      return this;
    }

    /**
     * <code>int32 CreatedTime = 9;</code>
     */
    public int getCreatedTime() {
      return instance.getCreatedTime();
    }
    /**
     * <code>int32 CreatedTime = 9;</code>
     */
    public Builder setCreatedTime(int value) {
      copyOnWrite();
      instance.setCreatedTime(value);
      return this;
    }
    /**
     * <code>int32 CreatedTime = 9;</code>
     */
    public Builder clearCreatedTime() {
      copyOnWrite();
      instance.clearCreatedTime();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PB_Comment)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ir.ms.pb.PB_Comment();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        ir.ms.pb.PB_Comment other = (ir.ms.pb.PB_Comment) arg1;
        id_ = visitor.visitInt(id_ != 0, id_,
            other.id_ != 0, other.id_);
        userId_ = visitor.visitInt(userId_ != 0, userId_,
            other.userId_ != 0, other.userId_);
        postId_ = visitor.visitInt(postId_ != 0, postId_,
            other.postId_ != 0, other.postId_);
        text_ = visitor.visitString(!text_.isEmpty(), text_,
            !other.text_.isEmpty(), other.text_);
        createdTime_ = visitor.visitInt(createdTime_ != 0, createdTime_,
            other.createdTime_ != 0, other.createdTime_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                id_ = input.readInt32();
                break;
              }
              case 24: {

                userId_ = input.readInt32();
                break;
              }
              case 40: {

                postId_ = input.readInt32();
                break;
              }
              case 58: {
                String s = input.readStringRequireUtf8();

                text_ = s;
                break;
              }
              case 72: {

                createdTime_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (ir.ms.pb.PB_Comment.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:PB_Comment)
  private static final ir.ms.pb.PB_Comment DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PB_Comment();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static ir.ms.pb.PB_Comment getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PB_Comment> PARSER;

  public static com.google.protobuf.Parser<PB_Comment> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

