// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_rpc_chat.proto

package ir.ms.pb;

public interface PB_ChatParam_EditMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_ChatParam_EditMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string RoomKey = 1;</code>
   */
  java.lang.String getRoomKey();
  /**
   * <code>string RoomKey = 1;</code>
   */
  com.google.protobuf.ByteString
      getRoomKeyBytes();

  /**
   * <code>int64 MessageId = 3;</code>
   */
  long getMessageId();

  /**
   * <code>string NewText = 4;</code>
   */
  java.lang.String getNewText();
  /**
   * <code>string NewText = 4;</code>
   */
  com.google.protobuf.ByteString
      getNewTextBytes();
}
