// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_rpc_chat.proto

package ir.ms.pb;

public interface PB_ChatParam_DeleteChatHistoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_ChatParam_DeleteChatHistory)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string ChatKey = 1;</code>
   */
  java.lang.String getChatKey();
  /**
   * <code>string ChatKey = 1;</code>
   */
  com.google.protobuf.ByteString
      getChatKeyBytes();

  /**
   * <pre>
   *must persent
   * </pre>
   *
   * <code>int64 FromMessageId = 2;</code>
   */
  long getFromMessageId();
}
