// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_views.proto

package ir.ms.pb;

public interface PB_ChatViewOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_ChatView)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   *use as RemoteId
   * </pre>
   *
   * <code>string ChatKey = 3;</code>
   */
  java.lang.String getChatKey();
  /**
   * <pre>
   *use as RemoteId
   * </pre>
   *
   * <code>string ChatKey = 3;</code>
   */
  com.google.protobuf.ByteString
      getChatKeyBytes();

  /**
   * <code>int64 ChatId = 1;</code>
   */
  long getChatId();

  /**
   * <code>int32 RoomTypeEnumId = 5;</code>
   */
  int getRoomTypeEnumId();

  /**
   * <code>int32 UserId = 7;</code>
   */
  int getUserId();

  /**
   * <code>int32 PeerUserId = 9;</code>
   */
  int getPeerUserId();

  /**
   * <code>int64 GroupId = 11;</code>
   */
  long getGroupId();

  /**
   * <code>int32 CreatedTime = 13;</code>
   */
  int getCreatedTime();

  /**
   * <code>int64 UpdatedMs = 15;</code>
   */
  long getUpdatedMs();

  /**
   * <code>int64 LastMessageId = 17;</code>
   */
  long getLastMessageId();

  /**
   * <code>int64 LastDeletedMessageId = 18;</code>
   */
  long getLastDeletedMessageId();

  /**
   * <code>int64 LastSeenMessageId = 19;</code>
   */
  long getLastSeenMessageId();

  /**
   * <code>int32 LastSeqSeen = 21;</code>
   */
  int getLastSeqSeen();

  /**
   * <code>int32 LastSeqDelete = 23;</code>
   */
  int getLastSeqDelete();

  /**
   * <code>int32 CurrentSeq = 25;</code>
   */
  int getCurrentSeq();

  /**
   * <code>.PB_UserView User = 100;</code>
   */
  boolean hasUser();
  /**
   * <code>.PB_UserView User = 100;</code>
   */
  ir.ms.pb.PB_UserView getUser();

  /**
   * <pre>
   *local
   * </pre>
   *
   * <code>int32 SharedMediaCount = 200;</code>
   */
  int getSharedMediaCount();

  /**
   * <code>int32 UnseenCount = 205;</code>
   */
  int getUnseenCount();

  /**
   * <code>.PB_MessageView FirstUnreadMessage = 210;</code>
   */
  boolean hasFirstUnreadMessage();
  /**
   * <code>.PB_MessageView FirstUnreadMessage = 210;</code>
   */
  ir.ms.pb.PB_MessageView getFirstUnreadMessage();

  /**
   * <code>.PB_MessageView LastMessage = 212;</code>
   */
  boolean hasLastMessage();
  /**
   * <code>.PB_MessageView LastMessage = 212;</code>
   */
  ir.ms.pb.PB_MessageView getLastMessage();
}
