// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_rpc_chat.proto

package ir.ms.pb;

public interface PB_ChatResponse_GetChatHistoryToOlderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_ChatResponse_GetChatHistoryToOlder)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .PB_MessageView MessagesViews = 1;</code>
   */
  java.util.List<ir.ms.pb.PB_MessageView> 
      getMessagesViewsList();
  /**
   * <code>repeated .PB_MessageView MessagesViews = 1;</code>
   */
  ir.ms.pb.PB_MessageView getMessagesViews(int index);
  /**
   * <code>repeated .PB_MessageView MessagesViews = 1;</code>
   */
  int getMessagesViewsCount();

  /**
   * <code>bool HasMore = 2;</code>
   */
  boolean getHasMore();
}
