// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_rpc_chat.proto

package ir.ms.pb;

/**
 * <pre>
 * GetChatHistoryToOlder
 * </pre>
 *
 * Protobuf type {@code PB_ChatParam_GetChatHistoryToOlder}
 */
public  final class PB_ChatParam_GetChatHistoryToOlder extends
    com.google.protobuf.GeneratedMessageLite<
        PB_ChatParam_GetChatHistoryToOlder, PB_ChatParam_GetChatHistoryToOlder.Builder> implements
    // @@protoc_insertion_point(message_implements:PB_ChatParam_GetChatHistoryToOlder)
    PB_ChatParam_GetChatHistoryToOlderOrBuilder {
  private PB_ChatParam_GetChatHistoryToOlder() {
    chatKey_ = "";
  }
  public static final int CHATKEY_FIELD_NUMBER = 1;
  private java.lang.String chatKey_;
  /**
   * <code>string ChatKey = 1;</code>
   */
  public java.lang.String getChatKey() {
    return chatKey_;
  }
  /**
   * <code>string ChatKey = 1;</code>
   */
  public com.google.protobuf.ByteString
      getChatKeyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(chatKey_);
  }
  /**
   * <code>string ChatKey = 1;</code>
   */
  private void setChatKey(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    chatKey_ = value;
  }
  /**
   * <code>string ChatKey = 1;</code>
   */
  private void clearChatKey() {
    
    chatKey_ = getDefaultInstance().getChatKey();
  }
  /**
   * <code>string ChatKey = 1;</code>
   */
  private void setChatKeyBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    chatKey_ = value.toStringUtf8();
  }

  public static final int LIMIT_FIELD_NUMBER = 2;
  private int limit_;
  /**
   * <code>int32 Limit = 2;</code>
   */
  public int getLimit() {
    return limit_;
  }
  /**
   * <code>int32 Limit = 2;</code>
   */
  private void setLimit(int value) {
    
    limit_ = value;
  }
  /**
   * <code>int32 Limit = 2;</code>
   */
  private void clearLimit() {
    
    limit_ = 0;
  }

  public static final int FROMTOPMESSAGEID_FIELD_NUMBER = 3;
  private long fromTopMessageId_;
  /**
   * <pre>
   *can be
   * </pre>
   *
   * <code>int64 FromTopMessageId = 3;</code>
   */
  public long getFromTopMessageId() {
    return fromTopMessageId_;
  }
  /**
   * <pre>
   *can be
   * </pre>
   *
   * <code>int64 FromTopMessageId = 3;</code>
   */
  private void setFromTopMessageId(long value) {
    
    fromTopMessageId_ = value;
  }
  /**
   * <pre>
   *can be
   * </pre>
   *
   * <code>int64 FromTopMessageId = 3;</code>
   */
  private void clearFromTopMessageId() {
    
    fromTopMessageId_ = 0L;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!chatKey_.isEmpty()) {
      output.writeString(1, getChatKey());
    }
    if (limit_ != 0) {
      output.writeInt32(2, limit_);
    }
    if (fromTopMessageId_ != 0L) {
      output.writeInt64(3, fromTopMessageId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!chatKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getChatKey());
    }
    if (limit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, limit_);
    }
    if (fromTopMessageId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, fromTopMessageId_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static ir.ms.pb.PB_ChatParam_GetChatHistoryToOlder parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ir.ms.pb.PB_ChatParam_GetChatHistoryToOlder parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ir.ms.pb.PB_ChatParam_GetChatHistoryToOlder parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ir.ms.pb.PB_ChatParam_GetChatHistoryToOlder parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ir.ms.pb.PB_ChatParam_GetChatHistoryToOlder parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ir.ms.pb.PB_ChatParam_GetChatHistoryToOlder parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ir.ms.pb.PB_ChatParam_GetChatHistoryToOlder parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static ir.ms.pb.PB_ChatParam_GetChatHistoryToOlder parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ir.ms.pb.PB_ChatParam_GetChatHistoryToOlder parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ir.ms.pb.PB_ChatParam_GetChatHistoryToOlder parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ir.ms.pb.PB_ChatParam_GetChatHistoryToOlder prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   * GetChatHistoryToOlder
   * </pre>
   *
   * Protobuf type {@code PB_ChatParam_GetChatHistoryToOlder}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        ir.ms.pb.PB_ChatParam_GetChatHistoryToOlder, Builder> implements
      // @@protoc_insertion_point(builder_implements:PB_ChatParam_GetChatHistoryToOlder)
      ir.ms.pb.PB_ChatParam_GetChatHistoryToOlderOrBuilder {
    // Construct using ir.ms.pb.PB_ChatParam_GetChatHistoryToOlder.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string ChatKey = 1;</code>
     */
    public java.lang.String getChatKey() {
      return instance.getChatKey();
    }
    /**
     * <code>string ChatKey = 1;</code>
     */
    public com.google.protobuf.ByteString
        getChatKeyBytes() {
      return instance.getChatKeyBytes();
    }
    /**
     * <code>string ChatKey = 1;</code>
     */
    public Builder setChatKey(
        java.lang.String value) {
      copyOnWrite();
      instance.setChatKey(value);
      return this;
    }
    /**
     * <code>string ChatKey = 1;</code>
     */
    public Builder clearChatKey() {
      copyOnWrite();
      instance.clearChatKey();
      return this;
    }
    /**
     * <code>string ChatKey = 1;</code>
     */
    public Builder setChatKeyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setChatKeyBytes(value);
      return this;
    }

    /**
     * <code>int32 Limit = 2;</code>
     */
    public int getLimit() {
      return instance.getLimit();
    }
    /**
     * <code>int32 Limit = 2;</code>
     */
    public Builder setLimit(int value) {
      copyOnWrite();
      instance.setLimit(value);
      return this;
    }
    /**
     * <code>int32 Limit = 2;</code>
     */
    public Builder clearLimit() {
      copyOnWrite();
      instance.clearLimit();
      return this;
    }

    /**
     * <pre>
     *can be
     * </pre>
     *
     * <code>int64 FromTopMessageId = 3;</code>
     */
    public long getFromTopMessageId() {
      return instance.getFromTopMessageId();
    }
    /**
     * <pre>
     *can be
     * </pre>
     *
     * <code>int64 FromTopMessageId = 3;</code>
     */
    public Builder setFromTopMessageId(long value) {
      copyOnWrite();
      instance.setFromTopMessageId(value);
      return this;
    }
    /**
     * <pre>
     *can be
     * </pre>
     *
     * <code>int64 FromTopMessageId = 3;</code>
     */
    public Builder clearFromTopMessageId() {
      copyOnWrite();
      instance.clearFromTopMessageId();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PB_ChatParam_GetChatHistoryToOlder)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ir.ms.pb.PB_ChatParam_GetChatHistoryToOlder();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        ir.ms.pb.PB_ChatParam_GetChatHistoryToOlder other = (ir.ms.pb.PB_ChatParam_GetChatHistoryToOlder) arg1;
        chatKey_ = visitor.visitString(!chatKey_.isEmpty(), chatKey_,
            !other.chatKey_.isEmpty(), other.chatKey_);
        limit_ = visitor.visitInt(limit_ != 0, limit_,
            other.limit_ != 0, other.limit_);
        fromTopMessageId_ = visitor.visitLong(fromTopMessageId_ != 0L, fromTopMessageId_,
            other.fromTopMessageId_ != 0L, other.fromTopMessageId_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                chatKey_ = s;
                break;
              }
              case 16: {

                limit_ = input.readInt32();
                break;
              }
              case 24: {

                fromTopMessageId_ = input.readInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (ir.ms.pb.PB_ChatParam_GetChatHistoryToOlder.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:PB_ChatParam_GetChatHistoryToOlder)
  private static final ir.ms.pb.PB_ChatParam_GetChatHistoryToOlder DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PB_ChatParam_GetChatHistoryToOlder();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static ir.ms.pb.PB_ChatParam_GetChatHistoryToOlder getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PB_ChatParam_GetChatHistoryToOlder> PARSER;

  public static com.google.protobuf.Parser<PB_ChatParam_GetChatHistoryToOlder> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

