// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_rpc_chat.proto

package ir.ms.pb;

public interface PB_ChatResponse_SetChatMessagesRangeAsSeenOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_ChatResponse_SetChatMessagesRangeAsSeen)
    com.google.protobuf.MessageLiteOrBuilder {
}
