// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_tables.proto

package ir.ms.pb;

public interface PB_DirectOfflineOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_DirectOffline)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 DirectOfflineId = 1;</code>
   */
  long getDirectOfflineId();

  /**
   * <code>int32 ToUserId = 3;</code>
   */
  int getToUserId();

  /**
   * <code>string ChatKey = 5;</code>
   */
  java.lang.String getChatKey();
  /**
   * <code>string ChatKey = 5;</code>
   */
  com.google.protobuf.ByteString
      getChatKeyBytes();

  /**
   * <code>int64 MessageId = 7;</code>
   */
  long getMessageId();

  /**
   * <code>int64 MessageFileId = 9;</code>
   */
  long getMessageFileId();

  /**
   * <code>string PBClass = 11;</code>
   */
  java.lang.String getPBClass();
  /**
   * <code>string PBClass = 11;</code>
   */
  com.google.protobuf.ByteString
      getPBClassBytes();

  /**
   * <code>bytes DataPB = 13;</code>
   */
  com.google.protobuf.ByteString getDataPB();

  /**
   * <code>string DataJson = 15;</code>
   */
  java.lang.String getDataJson();
  /**
   * <code>string DataJson = 15;</code>
   */
  com.google.protobuf.ByteString
      getDataJsonBytes();

  /**
   * <code>string DataTemp = 17;</code>
   */
  java.lang.String getDataTemp();
  /**
   * <code>string DataTemp = 17;</code>
   */
  com.google.protobuf.ByteString
      getDataTempBytes();

  /**
   * <code>int64 AtTimeMs = 19;</code>
   */
  long getAtTimeMs();
}
