// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_tables.proto

package ir.ms.pb;

public interface PB_LogChangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_LogChange)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 Id = 1;</code>
   */
  int getId();

  /**
   * <code>string T = 3;</code>
   */
  java.lang.String getT();
  /**
   * <code>string T = 3;</code>
   */
  com.google.protobuf.ByteString
      getTBytes();
}
