// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_rpc_msg.proto

package ir.ms.pb;

/**
 * <pre>
 *&#47;//////////////////////////////////
 * </pre>
 *
 * Protobuf type {@code PB_MsgParam_ForwardMessages}
 */
public  final class PB_MsgParam_ForwardMessages extends
    com.google.protobuf.GeneratedMessageLite<
        PB_MsgParam_ForwardMessages, PB_MsgParam_ForwardMessages.Builder> implements
    // @@protoc_insertion_point(message_implements:PB_MsgParam_ForwardMessages)
    PB_MsgParam_ForwardMessagesOrBuilder {
  private PB_MsgParam_ForwardMessages() {
    toDirectChatKeys_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    toGroupChatIds_ = emptyLongList();
  }
  private int bitField0_;
  public static final int MESSAGESCOLLECTIONS_FIELD_NUMBER = 1;
  private ir.ms.pb.PB_MessagesCollections messagesCollections_;
  /**
   * <pre>
   *    /&#42;repeated int64 DirectMessagesIds = 1;
   *    repeated int64 GroupMessagesIds = 2;*&#47;
   * </pre>
   *
   * <code>.PB_MessagesCollections MessagesCollections = 1;</code>
   */
  public boolean hasMessagesCollections() {
    return messagesCollections_ != null;
  }
  /**
   * <pre>
   *    /&#42;repeated int64 DirectMessagesIds = 1;
   *    repeated int64 GroupMessagesIds = 2;*&#47;
   * </pre>
   *
   * <code>.PB_MessagesCollections MessagesCollections = 1;</code>
   */
  public ir.ms.pb.PB_MessagesCollections getMessagesCollections() {
    return messagesCollections_ == null ? ir.ms.pb.PB_MessagesCollections.getDefaultInstance() : messagesCollections_;
  }
  /**
   * <pre>
   *    /&#42;repeated int64 DirectMessagesIds = 1;
   *    repeated int64 GroupMessagesIds = 2;*&#47;
   * </pre>
   *
   * <code>.PB_MessagesCollections MessagesCollections = 1;</code>
   */
  private void setMessagesCollections(ir.ms.pb.PB_MessagesCollections value) {
    if (value == null) {
      throw new NullPointerException();
    }
    messagesCollections_ = value;
    
    }
  /**
   * <pre>
   *    /&#42;repeated int64 DirectMessagesIds = 1;
   *    repeated int64 GroupMessagesIds = 2;*&#47;
   * </pre>
   *
   * <code>.PB_MessagesCollections MessagesCollections = 1;</code>
   */
  private void setMessagesCollections(
      ir.ms.pb.PB_MessagesCollections.Builder builderForValue) {
    messagesCollections_ = builderForValue.build();
    
  }
  /**
   * <pre>
   *    /&#42;repeated int64 DirectMessagesIds = 1;
   *    repeated int64 GroupMessagesIds = 2;*&#47;
   * </pre>
   *
   * <code>.PB_MessagesCollections MessagesCollections = 1;</code>
   */
  private void mergeMessagesCollections(ir.ms.pb.PB_MessagesCollections value) {
    if (messagesCollections_ != null &&
        messagesCollections_ != ir.ms.pb.PB_MessagesCollections.getDefaultInstance()) {
      messagesCollections_ =
        ir.ms.pb.PB_MessagesCollections.newBuilder(messagesCollections_).mergeFrom(value).buildPartial();
    } else {
      messagesCollections_ = value;
    }
    
  }
  /**
   * <pre>
   *    /&#42;repeated int64 DirectMessagesIds = 1;
   *    repeated int64 GroupMessagesIds = 2;*&#47;
   * </pre>
   *
   * <code>.PB_MessagesCollections MessagesCollections = 1;</code>
   */
  private void clearMessagesCollections() {  messagesCollections_ = null;
    
  }

  public static final int TODIRECTCHATKEYS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<String> toDirectChatKeys_;
  /**
   * <pre>
   *    repeated int64 ToDirectChatIds = 3;
   * </pre>
   *
   * <code>repeated string ToDirectChatKeys = 3;</code>
   */
  public java.util.List<String> getToDirectChatKeysList() {
    return toDirectChatKeys_;
  }
  /**
   * <pre>
   *    repeated int64 ToDirectChatIds = 3;
   * </pre>
   *
   * <code>repeated string ToDirectChatKeys = 3;</code>
   */
  public int getToDirectChatKeysCount() {
    return toDirectChatKeys_.size();
  }
  /**
   * <pre>
   *    repeated int64 ToDirectChatIds = 3;
   * </pre>
   *
   * <code>repeated string ToDirectChatKeys = 3;</code>
   */
  public java.lang.String getToDirectChatKeys(int index) {
    return toDirectChatKeys_.get(index);
  }
  /**
   * <pre>
   *    repeated int64 ToDirectChatIds = 3;
   * </pre>
   *
   * <code>repeated string ToDirectChatKeys = 3;</code>
   */
  public com.google.protobuf.ByteString
      getToDirectChatKeysBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        toDirectChatKeys_.get(index));
  }
  private void ensureToDirectChatKeysIsMutable() {
    if (!toDirectChatKeys_.isModifiable()) {
      toDirectChatKeys_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(toDirectChatKeys_);
     }
  }
  /**
   * <pre>
   *    repeated int64 ToDirectChatIds = 3;
   * </pre>
   *
   * <code>repeated string ToDirectChatKeys = 3;</code>
   */
  private void setToDirectChatKeys(
      int index, java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  ensureToDirectChatKeysIsMutable();
    toDirectChatKeys_.set(index, value);
  }
  /**
   * <pre>
   *    repeated int64 ToDirectChatIds = 3;
   * </pre>
   *
   * <code>repeated string ToDirectChatKeys = 3;</code>
   */
  private void addToDirectChatKeys(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  ensureToDirectChatKeysIsMutable();
    toDirectChatKeys_.add(value);
  }
  /**
   * <pre>
   *    repeated int64 ToDirectChatIds = 3;
   * </pre>
   *
   * <code>repeated string ToDirectChatKeys = 3;</code>
   */
  private void addAllToDirectChatKeys(
      java.lang.Iterable<java.lang.String> values) {
    ensureToDirectChatKeysIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, toDirectChatKeys_);
  }
  /**
   * <pre>
   *    repeated int64 ToDirectChatIds = 3;
   * </pre>
   *
   * <code>repeated string ToDirectChatKeys = 3;</code>
   */
  private void clearToDirectChatKeys() {
    toDirectChatKeys_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <pre>
   *    repeated int64 ToDirectChatIds = 3;
   * </pre>
   *
   * <code>repeated string ToDirectChatKeys = 3;</code>
   */
  private void addToDirectChatKeysBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    ensureToDirectChatKeysIsMutable();
    toDirectChatKeys_.add(value.toStringUtf8());
  }

  public static final int TOGROUPCHATIDS_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.LongList toGroupChatIds_;
  /**
   * <code>repeated int64 ToGroupChatIds = 4;</code>
   */
  public java.util.List<java.lang.Long>
      getToGroupChatIdsList() {
    return toGroupChatIds_;
  }
  /**
   * <code>repeated int64 ToGroupChatIds = 4;</code>
   */
  public int getToGroupChatIdsCount() {
    return toGroupChatIds_.size();
  }
  /**
   * <code>repeated int64 ToGroupChatIds = 4;</code>
   */
  public long getToGroupChatIds(int index) {
    return toGroupChatIds_.getLong(index);
  }
  private void ensureToGroupChatIdsIsMutable() {
    if (!toGroupChatIds_.isModifiable()) {
      toGroupChatIds_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(toGroupChatIds_);
     }
  }
  /**
   * <code>repeated int64 ToGroupChatIds = 4;</code>
   */
  private void setToGroupChatIds(
      int index, long value) {
    ensureToGroupChatIdsIsMutable();
    toGroupChatIds_.setLong(index, value);
  }
  /**
   * <code>repeated int64 ToGroupChatIds = 4;</code>
   */
  private void addToGroupChatIds(long value) {
    ensureToGroupChatIdsIsMutable();
    toGroupChatIds_.addLong(value);
  }
  /**
   * <code>repeated int64 ToGroupChatIds = 4;</code>
   */
  private void addAllToGroupChatIds(
      java.lang.Iterable<? extends java.lang.Long> values) {
    ensureToGroupChatIdsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, toGroupChatIds_);
  }
  /**
   * <code>repeated int64 ToGroupChatIds = 4;</code>
   */
  private void clearToGroupChatIds() {
    toGroupChatIds_ = emptyLongList();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (messagesCollections_ != null) {
      output.writeMessage(1, getMessagesCollections());
    }
    for (int i = 0; i < toDirectChatKeys_.size(); i++) {
      output.writeString(3, toDirectChatKeys_.get(i));
    }
    for (int i = 0; i < toGroupChatIds_.size(); i++) {
      output.writeInt64(4, toGroupChatIds_.getLong(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (messagesCollections_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMessagesCollections());
    }
    {
      int dataSize = 0;
      for (int i = 0; i < toDirectChatKeys_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeStringSizeNoTag(toDirectChatKeys_.get(i));
      }
      size += dataSize;
      size += 1 * getToDirectChatKeysList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < toGroupChatIds_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(toGroupChatIds_.getLong(i));
      }
      size += dataSize;
      size += 1 * getToGroupChatIdsList().size();
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static ir.ms.pb.PB_MsgParam_ForwardMessages parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ir.ms.pb.PB_MsgParam_ForwardMessages parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ir.ms.pb.PB_MsgParam_ForwardMessages parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ir.ms.pb.PB_MsgParam_ForwardMessages parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ir.ms.pb.PB_MsgParam_ForwardMessages parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ir.ms.pb.PB_MsgParam_ForwardMessages parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ir.ms.pb.PB_MsgParam_ForwardMessages parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static ir.ms.pb.PB_MsgParam_ForwardMessages parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ir.ms.pb.PB_MsgParam_ForwardMessages parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ir.ms.pb.PB_MsgParam_ForwardMessages parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ir.ms.pb.PB_MsgParam_ForwardMessages prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * <pre>
   *&#47;//////////////////////////////////
   * </pre>
   *
   * Protobuf type {@code PB_MsgParam_ForwardMessages}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        ir.ms.pb.PB_MsgParam_ForwardMessages, Builder> implements
      // @@protoc_insertion_point(builder_implements:PB_MsgParam_ForwardMessages)
      ir.ms.pb.PB_MsgParam_ForwardMessagesOrBuilder {
    // Construct using ir.ms.pb.PB_MsgParam_ForwardMessages.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     *    /&#42;repeated int64 DirectMessagesIds = 1;
     *    repeated int64 GroupMessagesIds = 2;*&#47;
     * </pre>
     *
     * <code>.PB_MessagesCollections MessagesCollections = 1;</code>
     */
    public boolean hasMessagesCollections() {
      return instance.hasMessagesCollections();
    }
    /**
     * <pre>
     *    /&#42;repeated int64 DirectMessagesIds = 1;
     *    repeated int64 GroupMessagesIds = 2;*&#47;
     * </pre>
     *
     * <code>.PB_MessagesCollections MessagesCollections = 1;</code>
     */
    public ir.ms.pb.PB_MessagesCollections getMessagesCollections() {
      return instance.getMessagesCollections();
    }
    /**
     * <pre>
     *    /&#42;repeated int64 DirectMessagesIds = 1;
     *    repeated int64 GroupMessagesIds = 2;*&#47;
     * </pre>
     *
     * <code>.PB_MessagesCollections MessagesCollections = 1;</code>
     */
    public Builder setMessagesCollections(ir.ms.pb.PB_MessagesCollections value) {
      copyOnWrite();
      instance.setMessagesCollections(value);
      return this;
      }
    /**
     * <pre>
     *    /&#42;repeated int64 DirectMessagesIds = 1;
     *    repeated int64 GroupMessagesIds = 2;*&#47;
     * </pre>
     *
     * <code>.PB_MessagesCollections MessagesCollections = 1;</code>
     */
    public Builder setMessagesCollections(
        ir.ms.pb.PB_MessagesCollections.Builder builderForValue) {
      copyOnWrite();
      instance.setMessagesCollections(builderForValue);
      return this;
    }
    /**
     * <pre>
     *    /&#42;repeated int64 DirectMessagesIds = 1;
     *    repeated int64 GroupMessagesIds = 2;*&#47;
     * </pre>
     *
     * <code>.PB_MessagesCollections MessagesCollections = 1;</code>
     */
    public Builder mergeMessagesCollections(ir.ms.pb.PB_MessagesCollections value) {
      copyOnWrite();
      instance.mergeMessagesCollections(value);
      return this;
    }
    /**
     * <pre>
     *    /&#42;repeated int64 DirectMessagesIds = 1;
     *    repeated int64 GroupMessagesIds = 2;*&#47;
     * </pre>
     *
     * <code>.PB_MessagesCollections MessagesCollections = 1;</code>
     */
    public Builder clearMessagesCollections() {  copyOnWrite();
      instance.clearMessagesCollections();
      return this;
    }

    /**
     * <pre>
     *    repeated int64 ToDirectChatIds = 3;
     * </pre>
     *
     * <code>repeated string ToDirectChatKeys = 3;</code>
     */
    public java.util.List<String>
        getToDirectChatKeysList() {
      return java.util.Collections.unmodifiableList(
          instance.getToDirectChatKeysList());
    }
    /**
     * <pre>
     *    repeated int64 ToDirectChatIds = 3;
     * </pre>
     *
     * <code>repeated string ToDirectChatKeys = 3;</code>
     */
    public int getToDirectChatKeysCount() {
      return instance.getToDirectChatKeysCount();
    }
    /**
     * <pre>
     *    repeated int64 ToDirectChatIds = 3;
     * </pre>
     *
     * <code>repeated string ToDirectChatKeys = 3;</code>
     */
    public java.lang.String getToDirectChatKeys(int index) {
      return instance.getToDirectChatKeys(index);
    }
    /**
     * <pre>
     *    repeated int64 ToDirectChatIds = 3;
     * </pre>
     *
     * <code>repeated string ToDirectChatKeys = 3;</code>
     */
    public com.google.protobuf.ByteString
        getToDirectChatKeysBytes(int index) {
      return instance.getToDirectChatKeysBytes(index);
    }
    /**
     * <pre>
     *    repeated int64 ToDirectChatIds = 3;
     * </pre>
     *
     * <code>repeated string ToDirectChatKeys = 3;</code>
     */
    public Builder setToDirectChatKeys(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setToDirectChatKeys(index, value);
      return this;
    }
    /**
     * <pre>
     *    repeated int64 ToDirectChatIds = 3;
     * </pre>
     *
     * <code>repeated string ToDirectChatKeys = 3;</code>
     */
    public Builder addToDirectChatKeys(
        java.lang.String value) {
      copyOnWrite();
      instance.addToDirectChatKeys(value);
      return this;
    }
    /**
     * <pre>
     *    repeated int64 ToDirectChatIds = 3;
     * </pre>
     *
     * <code>repeated string ToDirectChatKeys = 3;</code>
     */
    public Builder addAllToDirectChatKeys(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllToDirectChatKeys(values);
      return this;
    }
    /**
     * <pre>
     *    repeated int64 ToDirectChatIds = 3;
     * </pre>
     *
     * <code>repeated string ToDirectChatKeys = 3;</code>
     */
    public Builder clearToDirectChatKeys() {
      copyOnWrite();
      instance.clearToDirectChatKeys();
      return this;
    }
    /**
     * <pre>
     *    repeated int64 ToDirectChatIds = 3;
     * </pre>
     *
     * <code>repeated string ToDirectChatKeys = 3;</code>
     */
    public Builder addToDirectChatKeysBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addToDirectChatKeysBytes(value);
      return this;
    }

    /**
     * <code>repeated int64 ToGroupChatIds = 4;</code>
     */
    public java.util.List<java.lang.Long>
        getToGroupChatIdsList() {
      return java.util.Collections.unmodifiableList(
          instance.getToGroupChatIdsList());
    }
    /**
     * <code>repeated int64 ToGroupChatIds = 4;</code>
     */
    public int getToGroupChatIdsCount() {
      return instance.getToGroupChatIdsCount();
    }
    /**
     * <code>repeated int64 ToGroupChatIds = 4;</code>
     */
    public long getToGroupChatIds(int index) {
      return instance.getToGroupChatIds(index);
    }
    /**
     * <code>repeated int64 ToGroupChatIds = 4;</code>
     */
    public Builder setToGroupChatIds(
        int index, long value) {
      copyOnWrite();
      instance.setToGroupChatIds(index, value);
      return this;
    }
    /**
     * <code>repeated int64 ToGroupChatIds = 4;</code>
     */
    public Builder addToGroupChatIds(long value) {
      copyOnWrite();
      instance.addToGroupChatIds(value);
      return this;
    }
    /**
     * <code>repeated int64 ToGroupChatIds = 4;</code>
     */
    public Builder addAllToGroupChatIds(
        java.lang.Iterable<? extends java.lang.Long> values) {
      copyOnWrite();
      instance.addAllToGroupChatIds(values);
      return this;
    }
    /**
     * <code>repeated int64 ToGroupChatIds = 4;</code>
     */
    public Builder clearToGroupChatIds() {
      copyOnWrite();
      instance.clearToGroupChatIds();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PB_MsgParam_ForwardMessages)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ir.ms.pb.PB_MsgParam_ForwardMessages();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        toDirectChatKeys_.makeImmutable();
        toGroupChatIds_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        ir.ms.pb.PB_MsgParam_ForwardMessages other = (ir.ms.pb.PB_MsgParam_ForwardMessages) arg1;
        messagesCollections_ = visitor.visitMessage(messagesCollections_, other.messagesCollections_);
        toDirectChatKeys_= visitor.visitList(toDirectChatKeys_, other.toDirectChatKeys_);
        toGroupChatIds_= visitor.visitLongList(toGroupChatIds_, other.toGroupChatIds_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                ir.ms.pb.PB_MessagesCollections.Builder subBuilder = null;
                if (messagesCollections_ != null) {
                  subBuilder = messagesCollections_.toBuilder();
                }
                messagesCollections_ = input.readMessage(ir.ms.pb.PB_MessagesCollections.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(messagesCollections_);
                  messagesCollections_ = subBuilder.buildPartial();
                }

                break;
              }
              case 26: {
                String s = input.readStringRequireUtf8();
                if (!toDirectChatKeys_.isModifiable()) {
                  toDirectChatKeys_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(toDirectChatKeys_);
                }
                toDirectChatKeys_.add(s);
                break;
              }
              case 32: {
                if (!toGroupChatIds_.isModifiable()) {
                  toGroupChatIds_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(toGroupChatIds_);
                }
                toGroupChatIds_.addLong(input.readInt64());
                break;
              }
              case 34: {
                int length = input.readRawVarint32();
                int limit = input.pushLimit(length);
                if (!toGroupChatIds_.isModifiable() && input.getBytesUntilLimit() > 0) {
                  toGroupChatIds_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(toGroupChatIds_);
                }
                while (input.getBytesUntilLimit() > 0) {
                  toGroupChatIds_.addLong(input.readInt64());
                }
                input.popLimit(limit);
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (ir.ms.pb.PB_MsgParam_ForwardMessages.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:PB_MsgParam_ForwardMessages)
  private static final ir.ms.pb.PB_MsgParam_ForwardMessages DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PB_MsgParam_ForwardMessages();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static ir.ms.pb.PB_MsgParam_ForwardMessages getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PB_MsgParam_ForwardMessages> PARSER;

  public static com.google.protobuf.Parser<PB_MsgParam_ForwardMessages> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

