// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_tables.proto

package ir.ms.pb;

public interface PB_MessageFileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_MessageFile)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 MessageFileId = 1;</code>
   */
  long getMessageFileId();

  /**
   * <code>string MessageFileKey = 3;</code>
   */
  java.lang.String getMessageFileKey();
  /**
   * <code>string MessageFileKey = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageFileKeyBytes();

  /**
   * <code>int32 OriginalUserId = 5;</code>
   */
  int getOriginalUserId();

  /**
   * <code>string Name = 7;</code>
   */
  java.lang.String getName();
  /**
   * <code>string Name = 7;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 Size = 9;</code>
   */
  int getSize();

  /**
   * <code>int32 FileTypeEnumId = 11;</code>
   */
  int getFileTypeEnumId();

  /**
   * <code>int32 Width = 13;</code>
   */
  int getWidth();

  /**
   * <code>int32 Height = 15;</code>
   */
  int getHeight();

  /**
   * <code>int32 Duration = 17;</code>
   */
  int getDuration();

  /**
   * <code>string Extension = 19;</code>
   */
  java.lang.String getExtension();
  /**
   * <code>string Extension = 19;</code>
   */
  com.google.protobuf.ByteString
      getExtensionBytes();

  /**
   * <code>string HashMd5 = 21;</code>
   */
  java.lang.String getHashMd5();
  /**
   * <code>string HashMd5 = 21;</code>
   */
  com.google.protobuf.ByteString
      getHashMd5Bytes();

  /**
   * <code>int64 HashAccess = 23;</code>
   */
  long getHashAccess();

  /**
   * <code>int32 CreatedSe = 25;</code>
   */
  int getCreatedSe();

  /**
   * <code>string ServerSrc = 27;</code>
   */
  java.lang.String getServerSrc();
  /**
   * <code>string ServerSrc = 27;</code>
   */
  com.google.protobuf.ByteString
      getServerSrcBytes();

  /**
   * <code>string ServerPath = 29;</code>
   */
  java.lang.String getServerPath();
  /**
   * <code>string ServerPath = 29;</code>
   */
  com.google.protobuf.ByteString
      getServerPathBytes();

  /**
   * <code>string ServerThumbPath = 31;</code>
   */
  java.lang.String getServerThumbPath();
  /**
   * <code>string ServerThumbPath = 31;</code>
   */
  com.google.protobuf.ByteString
      getServerThumbPathBytes();

  /**
   * <code>string BucketId = 33;</code>
   */
  java.lang.String getBucketId();
  /**
   * <code>string BucketId = 33;</code>
   */
  com.google.protobuf.ByteString
      getBucketIdBytes();

  /**
   * <code>int32 ServerId = 35;</code>
   */
  int getServerId();

  /**
   * <code>int32 CanDel = 37;</code>
   */
  int getCanDel();
}
