// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_tables.proto

package ir.ms.pb;

/**
 * Protobuf type {@code PB_MessageFile}
 */
public  final class PB_MessageFile extends
    com.google.protobuf.GeneratedMessageLite<
        PB_MessageFile, PB_MessageFile.Builder> implements
    // @@protoc_insertion_point(message_implements:PB_MessageFile)
    PB_MessageFileOrBuilder {
  private PB_MessageFile() {
    messageFileKey_ = "";
    name_ = "";
    extension_ = "";
    hashMd5_ = "";
    serverSrc_ = "";
    serverPath_ = "";
    serverThumbPath_ = "";
    bucketId_ = "";
  }
  public static final int MESSAGEFILEID_FIELD_NUMBER = 1;
  private long messageFileId_;
  /**
   * <code>int64 MessageFileId = 1;</code>
   */
  public long getMessageFileId() {
    return messageFileId_;
  }
  /**
   * <code>int64 MessageFileId = 1;</code>
   */
  private void setMessageFileId(long value) {
    
    messageFileId_ = value;
  }
  /**
   * <code>int64 MessageFileId = 1;</code>
   */
  private void clearMessageFileId() {
    
    messageFileId_ = 0L;
  }

  public static final int MESSAGEFILEKEY_FIELD_NUMBER = 3;
  private java.lang.String messageFileKey_;
  /**
   * <code>string MessageFileKey = 3;</code>
   */
  public java.lang.String getMessageFileKey() {
    return messageFileKey_;
  }
  /**
   * <code>string MessageFileKey = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMessageFileKeyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(messageFileKey_);
  }
  /**
   * <code>string MessageFileKey = 3;</code>
   */
  private void setMessageFileKey(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    messageFileKey_ = value;
  }
  /**
   * <code>string MessageFileKey = 3;</code>
   */
  private void clearMessageFileKey() {
    
    messageFileKey_ = getDefaultInstance().getMessageFileKey();
  }
  /**
   * <code>string MessageFileKey = 3;</code>
   */
  private void setMessageFileKeyBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    messageFileKey_ = value.toStringUtf8();
  }

  public static final int ORIGINALUSERID_FIELD_NUMBER = 5;
  private int originalUserId_;
  /**
   * <code>int32 OriginalUserId = 5;</code>
   */
  public int getOriginalUserId() {
    return originalUserId_;
  }
  /**
   * <code>int32 OriginalUserId = 5;</code>
   */
  private void setOriginalUserId(int value) {
    
    originalUserId_ = value;
  }
  /**
   * <code>int32 OriginalUserId = 5;</code>
   */
  private void clearOriginalUserId() {
    
    originalUserId_ = 0;
  }

  public static final int NAME_FIELD_NUMBER = 7;
  private java.lang.String name_;
  /**
   * <code>string Name = 7;</code>
   */
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>string Name = 7;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>string Name = 7;</code>
   */
  private void setName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    name_ = value;
  }
  /**
   * <code>string Name = 7;</code>
   */
  private void clearName() {
    
    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>string Name = 7;</code>
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    name_ = value.toStringUtf8();
  }

  public static final int SIZE_FIELD_NUMBER = 9;
  private int size_;
  /**
   * <code>int32 Size = 9;</code>
   */
  public int getSize() {
    return size_;
  }
  /**
   * <code>int32 Size = 9;</code>
   */
  private void setSize(int value) {
    
    size_ = value;
  }
  /**
   * <code>int32 Size = 9;</code>
   */
  private void clearSize() {
    
    size_ = 0;
  }

  public static final int FILETYPEENUMID_FIELD_NUMBER = 11;
  private int fileTypeEnumId_;
  /**
   * <code>int32 FileTypeEnumId = 11;</code>
   */
  public int getFileTypeEnumId() {
    return fileTypeEnumId_;
  }
  /**
   * <code>int32 FileTypeEnumId = 11;</code>
   */
  private void setFileTypeEnumId(int value) {
    
    fileTypeEnumId_ = value;
  }
  /**
   * <code>int32 FileTypeEnumId = 11;</code>
   */
  private void clearFileTypeEnumId() {
    
    fileTypeEnumId_ = 0;
  }

  public static final int WIDTH_FIELD_NUMBER = 13;
  private int width_;
  /**
   * <code>int32 Width = 13;</code>
   */
  public int getWidth() {
    return width_;
  }
  /**
   * <code>int32 Width = 13;</code>
   */
  private void setWidth(int value) {
    
    width_ = value;
  }
  /**
   * <code>int32 Width = 13;</code>
   */
  private void clearWidth() {
    
    width_ = 0;
  }

  public static final int HEIGHT_FIELD_NUMBER = 15;
  private int height_;
  /**
   * <code>int32 Height = 15;</code>
   */
  public int getHeight() {
    return height_;
  }
  /**
   * <code>int32 Height = 15;</code>
   */
  private void setHeight(int value) {
    
    height_ = value;
  }
  /**
   * <code>int32 Height = 15;</code>
   */
  private void clearHeight() {
    
    height_ = 0;
  }

  public static final int DURATION_FIELD_NUMBER = 17;
  private int duration_;
  /**
   * <code>int32 Duration = 17;</code>
   */
  public int getDuration() {
    return duration_;
  }
  /**
   * <code>int32 Duration = 17;</code>
   */
  private void setDuration(int value) {
    
    duration_ = value;
  }
  /**
   * <code>int32 Duration = 17;</code>
   */
  private void clearDuration() {
    
    duration_ = 0;
  }

  public static final int EXTENSION_FIELD_NUMBER = 19;
  private java.lang.String extension_;
  /**
   * <code>string Extension = 19;</code>
   */
  public java.lang.String getExtension() {
    return extension_;
  }
  /**
   * <code>string Extension = 19;</code>
   */
  public com.google.protobuf.ByteString
      getExtensionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(extension_);
  }
  /**
   * <code>string Extension = 19;</code>
   */
  private void setExtension(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    extension_ = value;
  }
  /**
   * <code>string Extension = 19;</code>
   */
  private void clearExtension() {
    
    extension_ = getDefaultInstance().getExtension();
  }
  /**
   * <code>string Extension = 19;</code>
   */
  private void setExtensionBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    extension_ = value.toStringUtf8();
  }

  public static final int HASHMD5_FIELD_NUMBER = 21;
  private java.lang.String hashMd5_;
  /**
   * <code>string HashMd5 = 21;</code>
   */
  public java.lang.String getHashMd5() {
    return hashMd5_;
  }
  /**
   * <code>string HashMd5 = 21;</code>
   */
  public com.google.protobuf.ByteString
      getHashMd5Bytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(hashMd5_);
  }
  /**
   * <code>string HashMd5 = 21;</code>
   */
  private void setHashMd5(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    hashMd5_ = value;
  }
  /**
   * <code>string HashMd5 = 21;</code>
   */
  private void clearHashMd5() {
    
    hashMd5_ = getDefaultInstance().getHashMd5();
  }
  /**
   * <code>string HashMd5 = 21;</code>
   */
  private void setHashMd5Bytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    hashMd5_ = value.toStringUtf8();
  }

  public static final int HASHACCESS_FIELD_NUMBER = 23;
  private long hashAccess_;
  /**
   * <code>int64 HashAccess = 23;</code>
   */
  public long getHashAccess() {
    return hashAccess_;
  }
  /**
   * <code>int64 HashAccess = 23;</code>
   */
  private void setHashAccess(long value) {
    
    hashAccess_ = value;
  }
  /**
   * <code>int64 HashAccess = 23;</code>
   */
  private void clearHashAccess() {
    
    hashAccess_ = 0L;
  }

  public static final int CREATEDSE_FIELD_NUMBER = 25;
  private int createdSe_;
  /**
   * <code>int32 CreatedSe = 25;</code>
   */
  public int getCreatedSe() {
    return createdSe_;
  }
  /**
   * <code>int32 CreatedSe = 25;</code>
   */
  private void setCreatedSe(int value) {
    
    createdSe_ = value;
  }
  /**
   * <code>int32 CreatedSe = 25;</code>
   */
  private void clearCreatedSe() {
    
    createdSe_ = 0;
  }

  public static final int SERVERSRC_FIELD_NUMBER = 27;
  private java.lang.String serverSrc_;
  /**
   * <code>string ServerSrc = 27;</code>
   */
  public java.lang.String getServerSrc() {
    return serverSrc_;
  }
  /**
   * <code>string ServerSrc = 27;</code>
   */
  public com.google.protobuf.ByteString
      getServerSrcBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(serverSrc_);
  }
  /**
   * <code>string ServerSrc = 27;</code>
   */
  private void setServerSrc(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    serverSrc_ = value;
  }
  /**
   * <code>string ServerSrc = 27;</code>
   */
  private void clearServerSrc() {
    
    serverSrc_ = getDefaultInstance().getServerSrc();
  }
  /**
   * <code>string ServerSrc = 27;</code>
   */
  private void setServerSrcBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    serverSrc_ = value.toStringUtf8();
  }

  public static final int SERVERPATH_FIELD_NUMBER = 29;
  private java.lang.String serverPath_;
  /**
   * <code>string ServerPath = 29;</code>
   */
  public java.lang.String getServerPath() {
    return serverPath_;
  }
  /**
   * <code>string ServerPath = 29;</code>
   */
  public com.google.protobuf.ByteString
      getServerPathBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(serverPath_);
  }
  /**
   * <code>string ServerPath = 29;</code>
   */
  private void setServerPath(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    serverPath_ = value;
  }
  /**
   * <code>string ServerPath = 29;</code>
   */
  private void clearServerPath() {
    
    serverPath_ = getDefaultInstance().getServerPath();
  }
  /**
   * <code>string ServerPath = 29;</code>
   */
  private void setServerPathBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    serverPath_ = value.toStringUtf8();
  }

  public static final int SERVERTHUMBPATH_FIELD_NUMBER = 31;
  private java.lang.String serverThumbPath_;
  /**
   * <code>string ServerThumbPath = 31;</code>
   */
  public java.lang.String getServerThumbPath() {
    return serverThumbPath_;
  }
  /**
   * <code>string ServerThumbPath = 31;</code>
   */
  public com.google.protobuf.ByteString
      getServerThumbPathBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(serverThumbPath_);
  }
  /**
   * <code>string ServerThumbPath = 31;</code>
   */
  private void setServerThumbPath(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    serverThumbPath_ = value;
  }
  /**
   * <code>string ServerThumbPath = 31;</code>
   */
  private void clearServerThumbPath() {
    
    serverThumbPath_ = getDefaultInstance().getServerThumbPath();
  }
  /**
   * <code>string ServerThumbPath = 31;</code>
   */
  private void setServerThumbPathBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    serverThumbPath_ = value.toStringUtf8();
  }

  public static final int BUCKETID_FIELD_NUMBER = 33;
  private java.lang.String bucketId_;
  /**
   * <code>string BucketId = 33;</code>
   */
  public java.lang.String getBucketId() {
    return bucketId_;
  }
  /**
   * <code>string BucketId = 33;</code>
   */
  public com.google.protobuf.ByteString
      getBucketIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(bucketId_);
  }
  /**
   * <code>string BucketId = 33;</code>
   */
  private void setBucketId(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    bucketId_ = value;
  }
  /**
   * <code>string BucketId = 33;</code>
   */
  private void clearBucketId() {
    
    bucketId_ = getDefaultInstance().getBucketId();
  }
  /**
   * <code>string BucketId = 33;</code>
   */
  private void setBucketIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    bucketId_ = value.toStringUtf8();
  }

  public static final int SERVERID_FIELD_NUMBER = 35;
  private int serverId_;
  /**
   * <code>int32 ServerId = 35;</code>
   */
  public int getServerId() {
    return serverId_;
  }
  /**
   * <code>int32 ServerId = 35;</code>
   */
  private void setServerId(int value) {
    
    serverId_ = value;
  }
  /**
   * <code>int32 ServerId = 35;</code>
   */
  private void clearServerId() {
    
    serverId_ = 0;
  }

  public static final int CANDEL_FIELD_NUMBER = 37;
  private int canDel_;
  /**
   * <code>int32 CanDel = 37;</code>
   */
  public int getCanDel() {
    return canDel_;
  }
  /**
   * <code>int32 CanDel = 37;</code>
   */
  private void setCanDel(int value) {
    
    canDel_ = value;
  }
  /**
   * <code>int32 CanDel = 37;</code>
   */
  private void clearCanDel() {
    
    canDel_ = 0;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageFileId_ != 0L) {
      output.writeInt64(1, messageFileId_);
    }
    if (!messageFileKey_.isEmpty()) {
      output.writeString(3, getMessageFileKey());
    }
    if (originalUserId_ != 0) {
      output.writeInt32(5, originalUserId_);
    }
    if (!name_.isEmpty()) {
      output.writeString(7, getName());
    }
    if (size_ != 0) {
      output.writeInt32(9, size_);
    }
    if (fileTypeEnumId_ != 0) {
      output.writeInt32(11, fileTypeEnumId_);
    }
    if (width_ != 0) {
      output.writeInt32(13, width_);
    }
    if (height_ != 0) {
      output.writeInt32(15, height_);
    }
    if (duration_ != 0) {
      output.writeInt32(17, duration_);
    }
    if (!extension_.isEmpty()) {
      output.writeString(19, getExtension());
    }
    if (!hashMd5_.isEmpty()) {
      output.writeString(21, getHashMd5());
    }
    if (hashAccess_ != 0L) {
      output.writeInt64(23, hashAccess_);
    }
    if (createdSe_ != 0) {
      output.writeInt32(25, createdSe_);
    }
    if (!serverSrc_.isEmpty()) {
      output.writeString(27, getServerSrc());
    }
    if (!serverPath_.isEmpty()) {
      output.writeString(29, getServerPath());
    }
    if (!serverThumbPath_.isEmpty()) {
      output.writeString(31, getServerThumbPath());
    }
    if (!bucketId_.isEmpty()) {
      output.writeString(33, getBucketId());
    }
    if (serverId_ != 0) {
      output.writeInt32(35, serverId_);
    }
    if (canDel_ != 0) {
      output.writeInt32(37, canDel_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (messageFileId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, messageFileId_);
    }
    if (!messageFileKey_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(3, getMessageFileKey());
    }
    if (originalUserId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, originalUserId_);
    }
    if (!name_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(7, getName());
    }
    if (size_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, size_);
    }
    if (fileTypeEnumId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, fileTypeEnumId_);
    }
    if (width_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, width_);
    }
    if (height_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(15, height_);
    }
    if (duration_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(17, duration_);
    }
    if (!extension_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(19, getExtension());
    }
    if (!hashMd5_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(21, getHashMd5());
    }
    if (hashAccess_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(23, hashAccess_);
    }
    if (createdSe_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(25, createdSe_);
    }
    if (!serverSrc_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(27, getServerSrc());
    }
    if (!serverPath_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(29, getServerPath());
    }
    if (!serverThumbPath_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(31, getServerThumbPath());
    }
    if (!bucketId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(33, getBucketId());
    }
    if (serverId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(35, serverId_);
    }
    if (canDel_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(37, canDel_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static ir.ms.pb.PB_MessageFile parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ir.ms.pb.PB_MessageFile parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ir.ms.pb.PB_MessageFile parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ir.ms.pb.PB_MessageFile parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ir.ms.pb.PB_MessageFile parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ir.ms.pb.PB_MessageFile parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ir.ms.pb.PB_MessageFile parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static ir.ms.pb.PB_MessageFile parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ir.ms.pb.PB_MessageFile parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ir.ms.pb.PB_MessageFile parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ir.ms.pb.PB_MessageFile prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code PB_MessageFile}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        ir.ms.pb.PB_MessageFile, Builder> implements
      // @@protoc_insertion_point(builder_implements:PB_MessageFile)
      ir.ms.pb.PB_MessageFileOrBuilder {
    // Construct using ir.ms.pb.PB_MessageFile.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int64 MessageFileId = 1;</code>
     */
    public long getMessageFileId() {
      return instance.getMessageFileId();
    }
    /**
     * <code>int64 MessageFileId = 1;</code>
     */
    public Builder setMessageFileId(long value) {
      copyOnWrite();
      instance.setMessageFileId(value);
      return this;
    }
    /**
     * <code>int64 MessageFileId = 1;</code>
     */
    public Builder clearMessageFileId() {
      copyOnWrite();
      instance.clearMessageFileId();
      return this;
    }

    /**
     * <code>string MessageFileKey = 3;</code>
     */
    public java.lang.String getMessageFileKey() {
      return instance.getMessageFileKey();
    }
    /**
     * <code>string MessageFileKey = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageFileKeyBytes() {
      return instance.getMessageFileKeyBytes();
    }
    /**
     * <code>string MessageFileKey = 3;</code>
     */
    public Builder setMessageFileKey(
        java.lang.String value) {
      copyOnWrite();
      instance.setMessageFileKey(value);
      return this;
    }
    /**
     * <code>string MessageFileKey = 3;</code>
     */
    public Builder clearMessageFileKey() {
      copyOnWrite();
      instance.clearMessageFileKey();
      return this;
    }
    /**
     * <code>string MessageFileKey = 3;</code>
     */
    public Builder setMessageFileKeyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setMessageFileKeyBytes(value);
      return this;
    }

    /**
     * <code>int32 OriginalUserId = 5;</code>
     */
    public int getOriginalUserId() {
      return instance.getOriginalUserId();
    }
    /**
     * <code>int32 OriginalUserId = 5;</code>
     */
    public Builder setOriginalUserId(int value) {
      copyOnWrite();
      instance.setOriginalUserId(value);
      return this;
    }
    /**
     * <code>int32 OriginalUserId = 5;</code>
     */
    public Builder clearOriginalUserId() {
      copyOnWrite();
      instance.clearOriginalUserId();
      return this;
    }

    /**
     * <code>string Name = 7;</code>
     */
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>string Name = 7;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>string Name = 7;</code>
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>string Name = 7;</code>
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>string Name = 7;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>int32 Size = 9;</code>
     */
    public int getSize() {
      return instance.getSize();
    }
    /**
     * <code>int32 Size = 9;</code>
     */
    public Builder setSize(int value) {
      copyOnWrite();
      instance.setSize(value);
      return this;
    }
    /**
     * <code>int32 Size = 9;</code>
     */
    public Builder clearSize() {
      copyOnWrite();
      instance.clearSize();
      return this;
    }

    /**
     * <code>int32 FileTypeEnumId = 11;</code>
     */
    public int getFileTypeEnumId() {
      return instance.getFileTypeEnumId();
    }
    /**
     * <code>int32 FileTypeEnumId = 11;</code>
     */
    public Builder setFileTypeEnumId(int value) {
      copyOnWrite();
      instance.setFileTypeEnumId(value);
      return this;
    }
    /**
     * <code>int32 FileTypeEnumId = 11;</code>
     */
    public Builder clearFileTypeEnumId() {
      copyOnWrite();
      instance.clearFileTypeEnumId();
      return this;
    }

    /**
     * <code>int32 Width = 13;</code>
     */
    public int getWidth() {
      return instance.getWidth();
    }
    /**
     * <code>int32 Width = 13;</code>
     */
    public Builder setWidth(int value) {
      copyOnWrite();
      instance.setWidth(value);
      return this;
    }
    /**
     * <code>int32 Width = 13;</code>
     */
    public Builder clearWidth() {
      copyOnWrite();
      instance.clearWidth();
      return this;
    }

    /**
     * <code>int32 Height = 15;</code>
     */
    public int getHeight() {
      return instance.getHeight();
    }
    /**
     * <code>int32 Height = 15;</code>
     */
    public Builder setHeight(int value) {
      copyOnWrite();
      instance.setHeight(value);
      return this;
    }
    /**
     * <code>int32 Height = 15;</code>
     */
    public Builder clearHeight() {
      copyOnWrite();
      instance.clearHeight();
      return this;
    }

    /**
     * <code>int32 Duration = 17;</code>
     */
    public int getDuration() {
      return instance.getDuration();
    }
    /**
     * <code>int32 Duration = 17;</code>
     */
    public Builder setDuration(int value) {
      copyOnWrite();
      instance.setDuration(value);
      return this;
    }
    /**
     * <code>int32 Duration = 17;</code>
     */
    public Builder clearDuration() {
      copyOnWrite();
      instance.clearDuration();
      return this;
    }

    /**
     * <code>string Extension = 19;</code>
     */
    public java.lang.String getExtension() {
      return instance.getExtension();
    }
    /**
     * <code>string Extension = 19;</code>
     */
    public com.google.protobuf.ByteString
        getExtensionBytes() {
      return instance.getExtensionBytes();
    }
    /**
     * <code>string Extension = 19;</code>
     */
    public Builder setExtension(
        java.lang.String value) {
      copyOnWrite();
      instance.setExtension(value);
      return this;
    }
    /**
     * <code>string Extension = 19;</code>
     */
    public Builder clearExtension() {
      copyOnWrite();
      instance.clearExtension();
      return this;
    }
    /**
     * <code>string Extension = 19;</code>
     */
    public Builder setExtensionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setExtensionBytes(value);
      return this;
    }

    /**
     * <code>string HashMd5 = 21;</code>
     */
    public java.lang.String getHashMd5() {
      return instance.getHashMd5();
    }
    /**
     * <code>string HashMd5 = 21;</code>
     */
    public com.google.protobuf.ByteString
        getHashMd5Bytes() {
      return instance.getHashMd5Bytes();
    }
    /**
     * <code>string HashMd5 = 21;</code>
     */
    public Builder setHashMd5(
        java.lang.String value) {
      copyOnWrite();
      instance.setHashMd5(value);
      return this;
    }
    /**
     * <code>string HashMd5 = 21;</code>
     */
    public Builder clearHashMd5() {
      copyOnWrite();
      instance.clearHashMd5();
      return this;
    }
    /**
     * <code>string HashMd5 = 21;</code>
     */
    public Builder setHashMd5Bytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setHashMd5Bytes(value);
      return this;
    }

    /**
     * <code>int64 HashAccess = 23;</code>
     */
    public long getHashAccess() {
      return instance.getHashAccess();
    }
    /**
     * <code>int64 HashAccess = 23;</code>
     */
    public Builder setHashAccess(long value) {
      copyOnWrite();
      instance.setHashAccess(value);
      return this;
    }
    /**
     * <code>int64 HashAccess = 23;</code>
     */
    public Builder clearHashAccess() {
      copyOnWrite();
      instance.clearHashAccess();
      return this;
    }

    /**
     * <code>int32 CreatedSe = 25;</code>
     */
    public int getCreatedSe() {
      return instance.getCreatedSe();
    }
    /**
     * <code>int32 CreatedSe = 25;</code>
     */
    public Builder setCreatedSe(int value) {
      copyOnWrite();
      instance.setCreatedSe(value);
      return this;
    }
    /**
     * <code>int32 CreatedSe = 25;</code>
     */
    public Builder clearCreatedSe() {
      copyOnWrite();
      instance.clearCreatedSe();
      return this;
    }

    /**
     * <code>string ServerSrc = 27;</code>
     */
    public java.lang.String getServerSrc() {
      return instance.getServerSrc();
    }
    /**
     * <code>string ServerSrc = 27;</code>
     */
    public com.google.protobuf.ByteString
        getServerSrcBytes() {
      return instance.getServerSrcBytes();
    }
    /**
     * <code>string ServerSrc = 27;</code>
     */
    public Builder setServerSrc(
        java.lang.String value) {
      copyOnWrite();
      instance.setServerSrc(value);
      return this;
    }
    /**
     * <code>string ServerSrc = 27;</code>
     */
    public Builder clearServerSrc() {
      copyOnWrite();
      instance.clearServerSrc();
      return this;
    }
    /**
     * <code>string ServerSrc = 27;</code>
     */
    public Builder setServerSrcBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setServerSrcBytes(value);
      return this;
    }

    /**
     * <code>string ServerPath = 29;</code>
     */
    public java.lang.String getServerPath() {
      return instance.getServerPath();
    }
    /**
     * <code>string ServerPath = 29;</code>
     */
    public com.google.protobuf.ByteString
        getServerPathBytes() {
      return instance.getServerPathBytes();
    }
    /**
     * <code>string ServerPath = 29;</code>
     */
    public Builder setServerPath(
        java.lang.String value) {
      copyOnWrite();
      instance.setServerPath(value);
      return this;
    }
    /**
     * <code>string ServerPath = 29;</code>
     */
    public Builder clearServerPath() {
      copyOnWrite();
      instance.clearServerPath();
      return this;
    }
    /**
     * <code>string ServerPath = 29;</code>
     */
    public Builder setServerPathBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setServerPathBytes(value);
      return this;
    }

    /**
     * <code>string ServerThumbPath = 31;</code>
     */
    public java.lang.String getServerThumbPath() {
      return instance.getServerThumbPath();
    }
    /**
     * <code>string ServerThumbPath = 31;</code>
     */
    public com.google.protobuf.ByteString
        getServerThumbPathBytes() {
      return instance.getServerThumbPathBytes();
    }
    /**
     * <code>string ServerThumbPath = 31;</code>
     */
    public Builder setServerThumbPath(
        java.lang.String value) {
      copyOnWrite();
      instance.setServerThumbPath(value);
      return this;
    }
    /**
     * <code>string ServerThumbPath = 31;</code>
     */
    public Builder clearServerThumbPath() {
      copyOnWrite();
      instance.clearServerThumbPath();
      return this;
    }
    /**
     * <code>string ServerThumbPath = 31;</code>
     */
    public Builder setServerThumbPathBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setServerThumbPathBytes(value);
      return this;
    }

    /**
     * <code>string BucketId = 33;</code>
     */
    public java.lang.String getBucketId() {
      return instance.getBucketId();
    }
    /**
     * <code>string BucketId = 33;</code>
     */
    public com.google.protobuf.ByteString
        getBucketIdBytes() {
      return instance.getBucketIdBytes();
    }
    /**
     * <code>string BucketId = 33;</code>
     */
    public Builder setBucketId(
        java.lang.String value) {
      copyOnWrite();
      instance.setBucketId(value);
      return this;
    }
    /**
     * <code>string BucketId = 33;</code>
     */
    public Builder clearBucketId() {
      copyOnWrite();
      instance.clearBucketId();
      return this;
    }
    /**
     * <code>string BucketId = 33;</code>
     */
    public Builder setBucketIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBucketIdBytes(value);
      return this;
    }

    /**
     * <code>int32 ServerId = 35;</code>
     */
    public int getServerId() {
      return instance.getServerId();
    }
    /**
     * <code>int32 ServerId = 35;</code>
     */
    public Builder setServerId(int value) {
      copyOnWrite();
      instance.setServerId(value);
      return this;
    }
    /**
     * <code>int32 ServerId = 35;</code>
     */
    public Builder clearServerId() {
      copyOnWrite();
      instance.clearServerId();
      return this;
    }

    /**
     * <code>int32 CanDel = 37;</code>
     */
    public int getCanDel() {
      return instance.getCanDel();
    }
    /**
     * <code>int32 CanDel = 37;</code>
     */
    public Builder setCanDel(int value) {
      copyOnWrite();
      instance.setCanDel(value);
      return this;
    }
    /**
     * <code>int32 CanDel = 37;</code>
     */
    public Builder clearCanDel() {
      copyOnWrite();
      instance.clearCanDel();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PB_MessageFile)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ir.ms.pb.PB_MessageFile();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        ir.ms.pb.PB_MessageFile other = (ir.ms.pb.PB_MessageFile) arg1;
        messageFileId_ = visitor.visitLong(messageFileId_ != 0L, messageFileId_,
            other.messageFileId_ != 0L, other.messageFileId_);
        messageFileKey_ = visitor.visitString(!messageFileKey_.isEmpty(), messageFileKey_,
            !other.messageFileKey_.isEmpty(), other.messageFileKey_);
        originalUserId_ = visitor.visitInt(originalUserId_ != 0, originalUserId_,
            other.originalUserId_ != 0, other.originalUserId_);
        name_ = visitor.visitString(!name_.isEmpty(), name_,
            !other.name_.isEmpty(), other.name_);
        size_ = visitor.visitInt(size_ != 0, size_,
            other.size_ != 0, other.size_);
        fileTypeEnumId_ = visitor.visitInt(fileTypeEnumId_ != 0, fileTypeEnumId_,
            other.fileTypeEnumId_ != 0, other.fileTypeEnumId_);
        width_ = visitor.visitInt(width_ != 0, width_,
            other.width_ != 0, other.width_);
        height_ = visitor.visitInt(height_ != 0, height_,
            other.height_ != 0, other.height_);
        duration_ = visitor.visitInt(duration_ != 0, duration_,
            other.duration_ != 0, other.duration_);
        extension_ = visitor.visitString(!extension_.isEmpty(), extension_,
            !other.extension_.isEmpty(), other.extension_);
        hashMd5_ = visitor.visitString(!hashMd5_.isEmpty(), hashMd5_,
            !other.hashMd5_.isEmpty(), other.hashMd5_);
        hashAccess_ = visitor.visitLong(hashAccess_ != 0L, hashAccess_,
            other.hashAccess_ != 0L, other.hashAccess_);
        createdSe_ = visitor.visitInt(createdSe_ != 0, createdSe_,
            other.createdSe_ != 0, other.createdSe_);
        serverSrc_ = visitor.visitString(!serverSrc_.isEmpty(), serverSrc_,
            !other.serverSrc_.isEmpty(), other.serverSrc_);
        serverPath_ = visitor.visitString(!serverPath_.isEmpty(), serverPath_,
            !other.serverPath_.isEmpty(), other.serverPath_);
        serverThumbPath_ = visitor.visitString(!serverThumbPath_.isEmpty(), serverThumbPath_,
            !other.serverThumbPath_.isEmpty(), other.serverThumbPath_);
        bucketId_ = visitor.visitString(!bucketId_.isEmpty(), bucketId_,
            !other.bucketId_.isEmpty(), other.bucketId_);
        serverId_ = visitor.visitInt(serverId_ != 0, serverId_,
            other.serverId_ != 0, other.serverId_);
        canDel_ = visitor.visitInt(canDel_ != 0, canDel_,
            other.canDel_ != 0, other.canDel_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                messageFileId_ = input.readInt64();
                break;
              }
              case 26: {
                String s = input.readStringRequireUtf8();

                messageFileKey_ = s;
                break;
              }
              case 40: {

                originalUserId_ = input.readInt32();
                break;
              }
              case 58: {
                String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 72: {

                size_ = input.readInt32();
                break;
              }
              case 88: {

                fileTypeEnumId_ = input.readInt32();
                break;
              }
              case 104: {

                width_ = input.readInt32();
                break;
              }
              case 120: {

                height_ = input.readInt32();
                break;
              }
              case 136: {

                duration_ = input.readInt32();
                break;
              }
              case 154: {
                String s = input.readStringRequireUtf8();

                extension_ = s;
                break;
              }
              case 170: {
                String s = input.readStringRequireUtf8();

                hashMd5_ = s;
                break;
              }
              case 184: {

                hashAccess_ = input.readInt64();
                break;
              }
              case 200: {

                createdSe_ = input.readInt32();
                break;
              }
              case 218: {
                String s = input.readStringRequireUtf8();

                serverSrc_ = s;
                break;
              }
              case 234: {
                String s = input.readStringRequireUtf8();

                serverPath_ = s;
                break;
              }
              case 250: {
                String s = input.readStringRequireUtf8();

                serverThumbPath_ = s;
                break;
              }
              case 266: {
                String s = input.readStringRequireUtf8();

                bucketId_ = s;
                break;
              }
              case 280: {

                serverId_ = input.readInt32();
                break;
              }
              case 296: {

                canDel_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (ir.ms.pb.PB_MessageFile.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:PB_MessageFile)
  private static final ir.ms.pb.PB_MessageFile DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PB_MessageFile();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static ir.ms.pb.PB_MessageFile getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PB_MessageFile> PARSER;

  public static com.google.protobuf.Parser<PB_MessageFile> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

