// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_rpc_msg.proto

package ir.ms.pb;

public interface PB_MsgResponse_GetFreshChatListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_MsgResponse_GetFreshChatList)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .PB_ChatView Chats = 1;</code>
   */
  java.util.List<ir.ms.pb.PB_ChatView> 
      getChatsList();
  /**
   * <code>repeated .PB_ChatView Chats = 1;</code>
   */
  ir.ms.pb.PB_ChatView getChats(int index);
  /**
   * <code>repeated .PB_ChatView Chats = 1;</code>
   */
  int getChatsCount();

  /**
   * <pre>
   *dep
   * </pre>
   *
   * <code>repeated .PB_UserView Users = 6;</code>
   */
  java.util.List<ir.ms.pb.PB_UserView> 
      getUsersList();
  /**
   * <pre>
   *dep
   * </pre>
   *
   * <code>repeated .PB_UserView Users = 6;</code>
   */
  ir.ms.pb.PB_UserView getUsers(int index);
  /**
   * <pre>
   *dep
   * </pre>
   *
   * <code>repeated .PB_UserView Users = 6;</code>
   */
  int getUsersCount();
}
