// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_rpc_msg.proto

package ir.ms.pb;

public interface PB_MsgParam_DeleteChatHistoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_MsgParam_DeleteChatHistory)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   *int64 ChatId = 1 ;sint32 ChatKey = 21;
   * </pre>
   *
   * <code>string ChatKey = 1;</code>
   */
  java.lang.String getChatKey();
  /**
   * <pre>
   *int64 ChatId = 1 ;sint32 ChatKey = 21;
   * </pre>
   *
   * <code>string ChatKey = 1;</code>
   */
  com.google.protobuf.ByteString
      getChatKeyBytes();

  /**
   * <pre>
   *must persent
   * </pre>
   *
   * <code>sint32 ToSeq = 2;</code>
   */
  int getToSeq();
}
