// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_tables.proto

package ir.ms.pb;

public interface PB_NotificationRemovedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_NotificationRemoved)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 NotificationId = 1;</code>
   */
  int getNotificationId();

  /**
   * <code>int32 ForUserId = 3;</code>
   */
  int getForUserId();
}
