// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_tables.proto

package ir.ms.pb;

public interface PB_OldMsgPushOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_OldMsgPush)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 Id = 1;</code>
   */
  long getId();

  /**
   * <code>int64 Uid = 3;</code>
   */
  long getUid();

  /**
   * <code>int64 ToUser = 5;</code>
   */
  long getToUser();

  /**
   * <code>int64 MsgUid = 7;</code>
   */
  long getMsgUid();

  /**
   * <code>int64 CreatedTimeMs = 9;</code>
   */
  long getCreatedTimeMs();
}
