// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_tables.proto

package ir.ms.pb;

public interface PB_OldMsgPushEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_OldMsgPushEvent)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 Id = 1;</code>
   */
  long getId();

  /**
   * <code>int64 Uid = 3;</code>
   */
  long getUid();

  /**
   * <code>int32 ToUserId = 5;</code>
   */
  int getToUserId();

  /**
   * <code>int64 MsgUid = 7;</code>
   */
  long getMsgUid();

  /**
   * <code>string MsgKey = 9;</code>
   */
  java.lang.String getMsgKey();
  /**
   * <code>string MsgKey = 9;</code>
   */
  com.google.protobuf.ByteString
      getMsgKeyBytes();

  /**
   * <code>string RoomKey = 11;</code>
   */
  java.lang.String getRoomKey();
  /**
   * <code>string RoomKey = 11;</code>
   */
  com.google.protobuf.ByteString
      getRoomKeyBytes();

  /**
   * <code>int32 PeerUserId = 13;</code>
   */
  int getPeerUserId();

  /**
   * <code>int32 EventType = 15;</code>
   */
  int getEventType();

  /**
   * <code>int32 AtTime = 17;</code>
   */
  int getAtTime();
}
