// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_tables.proto

package ir.ms.pb;

public interface PB_SettingNotificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_SettingNotification)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 UserId = 1;</code>
   */
  int getUserId();

  /**
   * <code>int32 SocialLedOn = 3;</code>
   */
  int getSocialLedOn();

  /**
   * <code>string SocialLedColor = 5;</code>
   */
  java.lang.String getSocialLedColor();
  /**
   * <code>string SocialLedColor = 5;</code>
   */
  com.google.protobuf.ByteString
      getSocialLedColorBytes();

  /**
   * <code>int32 ReqestToFollowYou = 7;</code>
   */
  int getReqestToFollowYou();

  /**
   * <code>int32 FollowedYou = 9;</code>
   */
  int getFollowedYou();

  /**
   * <code>int32 AccptedYourFollowRequest = 11;</code>
   */
  int getAccptedYourFollowRequest();

  /**
   * <code>int32 YourPostLiked = 13;</code>
   */
  int getYourPostLiked();

  /**
   * <code>int32 YourPostCommented = 15;</code>
   */
  int getYourPostCommented();

  /**
   * <code>int32 MenthenedYouInPost = 17;</code>
   */
  int getMenthenedYouInPost();

  /**
   * <code>int32 MenthenedYouInComment = 19;</code>
   */
  int getMenthenedYouInComment();

  /**
   * <code>int32 YourContactsJoined = 21;</code>
   */
  int getYourContactsJoined();

  /**
   * <code>int32 DirectMessage = 23;</code>
   */
  int getDirectMessage();

  /**
   * <code>int32 DirectAlert = 25;</code>
   */
  int getDirectAlert();

  /**
   * <code>int32 DirectPerview = 27;</code>
   */
  int getDirectPerview();

  /**
   * <code>int32 DirectLedOn = 29;</code>
   */
  int getDirectLedOn();

  /**
   * <code>int32 DirectLedColor = 31;</code>
   */
  int getDirectLedColor();

  /**
   * <code>int32 DirectVibrate = 33;</code>
   */
  int getDirectVibrate();

  /**
   * <code>int32 DirectPopup = 35;</code>
   */
  int getDirectPopup();

  /**
   * <code>int32 DirectSound = 37;</code>
   */
  int getDirectSound();

  /**
   * <code>int32 DirectPriority = 39;</code>
   */
  int getDirectPriority();
}
