// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_tables.proto

package ir.ms.pb;

/**
 * Protobuf type {@code PB_TriggerLog}
 */
public  final class PB_TriggerLog extends
    com.google.protobuf.GeneratedMessageLite<
        PB_TriggerLog, PB_TriggerLog.Builder> implements
    // @@protoc_insertion_point(message_implements:PB_TriggerLog)
    PB_TriggerLogOrBuilder {
  private PB_TriggerLog() {
    modelName_ = "";
    changeType_ = "";
    targetStr_ = "";
  }
  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 Id = 1;</code>
   */
  public long getId() {
    return id_;
  }
  /**
   * <code>int64 Id = 1;</code>
   */
  private void setId(long value) {
    
    id_ = value;
  }
  /**
   * <code>int64 Id = 1;</code>
   */
  private void clearId() {
    
    id_ = 0L;
  }

  public static final int MODELNAME_FIELD_NUMBER = 3;
  private java.lang.String modelName_;
  /**
   * <code>string ModelName = 3;</code>
   */
  public java.lang.String getModelName() {
    return modelName_;
  }
  /**
   * <code>string ModelName = 3;</code>
   */
  public com.google.protobuf.ByteString
      getModelNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(modelName_);
  }
  /**
   * <code>string ModelName = 3;</code>
   */
  private void setModelName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    modelName_ = value;
  }
  /**
   * <code>string ModelName = 3;</code>
   */
  private void clearModelName() {
    
    modelName_ = getDefaultInstance().getModelName();
  }
  /**
   * <code>string ModelName = 3;</code>
   */
  private void setModelNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    modelName_ = value.toStringUtf8();
  }

  public static final int CHANGETYPE_FIELD_NUMBER = 5;
  private java.lang.String changeType_;
  /**
   * <code>string ChangeType = 5;</code>
   */
  public java.lang.String getChangeType() {
    return changeType_;
  }
  /**
   * <code>string ChangeType = 5;</code>
   */
  public com.google.protobuf.ByteString
      getChangeTypeBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(changeType_);
  }
  /**
   * <code>string ChangeType = 5;</code>
   */
  private void setChangeType(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    changeType_ = value;
  }
  /**
   * <code>string ChangeType = 5;</code>
   */
  private void clearChangeType() {
    
    changeType_ = getDefaultInstance().getChangeType();
  }
  /**
   * <code>string ChangeType = 5;</code>
   */
  private void setChangeTypeBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    changeType_ = value.toStringUtf8();
  }

  public static final int TARGETID_FIELD_NUMBER = 7;
  private long targetId_;
  /**
   * <code>int64 TargetId = 7;</code>
   */
  public long getTargetId() {
    return targetId_;
  }
  /**
   * <code>int64 TargetId = 7;</code>
   */
  private void setTargetId(long value) {
    
    targetId_ = value;
  }
  /**
   * <code>int64 TargetId = 7;</code>
   */
  private void clearTargetId() {
    
    targetId_ = 0L;
  }

  public static final int TARGETSTR_FIELD_NUMBER = 9;
  private java.lang.String targetStr_;
  /**
   * <code>string TargetStr = 9;</code>
   */
  public java.lang.String getTargetStr() {
    return targetStr_;
  }
  /**
   * <code>string TargetStr = 9;</code>
   */
  public com.google.protobuf.ByteString
      getTargetStrBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(targetStr_);
  }
  /**
   * <code>string TargetStr = 9;</code>
   */
  private void setTargetStr(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    targetStr_ = value;
  }
  /**
   * <code>string TargetStr = 9;</code>
   */
  private void clearTargetStr() {
    
    targetStr_ = getDefaultInstance().getTargetStr();
  }
  /**
   * <code>string TargetStr = 9;</code>
   */
  private void setTargetStrBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    targetStr_ = value.toStringUtf8();
  }

  public static final int CREATEDSE_FIELD_NUMBER = 11;
  private int createdSe_;
  /**
   * <code>int32 CreatedSe = 11;</code>
   */
  public int getCreatedSe() {
    return createdSe_;
  }
  /**
   * <code>int32 CreatedSe = 11;</code>
   */
  private void setCreatedSe(int value) {
    
    createdSe_ = value;
  }
  /**
   * <code>int32 CreatedSe = 11;</code>
   */
  private void clearCreatedSe() {
    
    createdSe_ = 0;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!modelName_.isEmpty()) {
      output.writeString(3, getModelName());
    }
    if (!changeType_.isEmpty()) {
      output.writeString(5, getChangeType());
    }
    if (targetId_ != 0L) {
      output.writeInt64(7, targetId_);
    }
    if (!targetStr_.isEmpty()) {
      output.writeString(9, getTargetStr());
    }
    if (createdSe_ != 0) {
      output.writeInt32(11, createdSe_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!modelName_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(3, getModelName());
    }
    if (!changeType_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(5, getChangeType());
    }
    if (targetId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, targetId_);
    }
    if (!targetStr_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(9, getTargetStr());
    }
    if (createdSe_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, createdSe_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static ir.ms.pb.PB_TriggerLog parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ir.ms.pb.PB_TriggerLog parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ir.ms.pb.PB_TriggerLog parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static ir.ms.pb.PB_TriggerLog parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static ir.ms.pb.PB_TriggerLog parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ir.ms.pb.PB_TriggerLog parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ir.ms.pb.PB_TriggerLog parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static ir.ms.pb.PB_TriggerLog parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static ir.ms.pb.PB_TriggerLog parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static ir.ms.pb.PB_TriggerLog parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ir.ms.pb.PB_TriggerLog prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code PB_TriggerLog}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        ir.ms.pb.PB_TriggerLog, Builder> implements
      // @@protoc_insertion_point(builder_implements:PB_TriggerLog)
      ir.ms.pb.PB_TriggerLogOrBuilder {
    // Construct using ir.ms.pb.PB_TriggerLog.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int64 Id = 1;</code>
     */
    public long getId() {
      return instance.getId();
    }
    /**
     * <code>int64 Id = 1;</code>
     */
    public Builder setId(long value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>int64 Id = 1;</code>
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }

    /**
     * <code>string ModelName = 3;</code>
     */
    public java.lang.String getModelName() {
      return instance.getModelName();
    }
    /**
     * <code>string ModelName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getModelNameBytes() {
      return instance.getModelNameBytes();
    }
    /**
     * <code>string ModelName = 3;</code>
     */
    public Builder setModelName(
        java.lang.String value) {
      copyOnWrite();
      instance.setModelName(value);
      return this;
    }
    /**
     * <code>string ModelName = 3;</code>
     */
    public Builder clearModelName() {
      copyOnWrite();
      instance.clearModelName();
      return this;
    }
    /**
     * <code>string ModelName = 3;</code>
     */
    public Builder setModelNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setModelNameBytes(value);
      return this;
    }

    /**
     * <code>string ChangeType = 5;</code>
     */
    public java.lang.String getChangeType() {
      return instance.getChangeType();
    }
    /**
     * <code>string ChangeType = 5;</code>
     */
    public com.google.protobuf.ByteString
        getChangeTypeBytes() {
      return instance.getChangeTypeBytes();
    }
    /**
     * <code>string ChangeType = 5;</code>
     */
    public Builder setChangeType(
        java.lang.String value) {
      copyOnWrite();
      instance.setChangeType(value);
      return this;
    }
    /**
     * <code>string ChangeType = 5;</code>
     */
    public Builder clearChangeType() {
      copyOnWrite();
      instance.clearChangeType();
      return this;
    }
    /**
     * <code>string ChangeType = 5;</code>
     */
    public Builder setChangeTypeBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setChangeTypeBytes(value);
      return this;
    }

    /**
     * <code>int64 TargetId = 7;</code>
     */
    public long getTargetId() {
      return instance.getTargetId();
    }
    /**
     * <code>int64 TargetId = 7;</code>
     */
    public Builder setTargetId(long value) {
      copyOnWrite();
      instance.setTargetId(value);
      return this;
    }
    /**
     * <code>int64 TargetId = 7;</code>
     */
    public Builder clearTargetId() {
      copyOnWrite();
      instance.clearTargetId();
      return this;
    }

    /**
     * <code>string TargetStr = 9;</code>
     */
    public java.lang.String getTargetStr() {
      return instance.getTargetStr();
    }
    /**
     * <code>string TargetStr = 9;</code>
     */
    public com.google.protobuf.ByteString
        getTargetStrBytes() {
      return instance.getTargetStrBytes();
    }
    /**
     * <code>string TargetStr = 9;</code>
     */
    public Builder setTargetStr(
        java.lang.String value) {
      copyOnWrite();
      instance.setTargetStr(value);
      return this;
    }
    /**
     * <code>string TargetStr = 9;</code>
     */
    public Builder clearTargetStr() {
      copyOnWrite();
      instance.clearTargetStr();
      return this;
    }
    /**
     * <code>string TargetStr = 9;</code>
     */
    public Builder setTargetStrBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTargetStrBytes(value);
      return this;
    }

    /**
     * <code>int32 CreatedSe = 11;</code>
     */
    public int getCreatedSe() {
      return instance.getCreatedSe();
    }
    /**
     * <code>int32 CreatedSe = 11;</code>
     */
    public Builder setCreatedSe(int value) {
      copyOnWrite();
      instance.setCreatedSe(value);
      return this;
    }
    /**
     * <code>int32 CreatedSe = 11;</code>
     */
    public Builder clearCreatedSe() {
      copyOnWrite();
      instance.clearCreatedSe();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PB_TriggerLog)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new ir.ms.pb.PB_TriggerLog();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        ir.ms.pb.PB_TriggerLog other = (ir.ms.pb.PB_TriggerLog) arg1;
        id_ = visitor.visitLong(id_ != 0L, id_,
            other.id_ != 0L, other.id_);
        modelName_ = visitor.visitString(!modelName_.isEmpty(), modelName_,
            !other.modelName_.isEmpty(), other.modelName_);
        changeType_ = visitor.visitString(!changeType_.isEmpty(), changeType_,
            !other.changeType_.isEmpty(), other.changeType_);
        targetId_ = visitor.visitLong(targetId_ != 0L, targetId_,
            other.targetId_ != 0L, other.targetId_);
        targetStr_ = visitor.visitString(!targetStr_.isEmpty(), targetStr_,
            !other.targetStr_.isEmpty(), other.targetStr_);
        createdSe_ = visitor.visitInt(createdSe_ != 0, createdSe_,
            other.createdSe_ != 0, other.createdSe_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                id_ = input.readInt64();
                break;
              }
              case 26: {
                String s = input.readStringRequireUtf8();

                modelName_ = s;
                break;
              }
              case 42: {
                String s = input.readStringRequireUtf8();

                changeType_ = s;
                break;
              }
              case 56: {

                targetId_ = input.readInt64();
                break;
              }
              case 74: {
                String s = input.readStringRequireUtf8();

                targetStr_ = s;
                break;
              }
              case 88: {

                createdSe_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (ir.ms.pb.PB_TriggerLog.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:PB_TriggerLog)
  private static final ir.ms.pb.PB_TriggerLog DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PB_TriggerLog();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static ir.ms.pb.PB_TriggerLog getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PB_TriggerLog> PARSER;

  public static com.google.protobuf.Parser<PB_TriggerLog> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

