// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_updates.proto

package ir.ms.pb;

public interface PB_UpdateGroupParticipantsOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:PB_UpdateGroupParticipants)
    com.google.protobuf.MessageLiteOrBuilder {}
