// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_rpc_auth2.proto

package ir.ms.pb;

public interface PB_UserParam_CheckUserName2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_UserParam_CheckUserName2)
    com.google.protobuf.MessageLiteOrBuilder {
}
