// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_rpc_user.proto

package ir.ms.pb;

public interface PB_UserParam_UpdateAboutOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_UserParam_UpdateAbout)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string NewAbout = 1;</code>
   */
  java.lang.String getNewAbout();
  /**
   * <code>string NewAbout = 1;</code>
   */
  com.google.protobuf.ByteString
      getNewAboutBytes();
}
