// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: global.proto

package ir.ms.pb;

public final class PB {
  private PB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
