// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_global.proto

package ir.ms.pb;

public interface PB_CommandReceivedToServerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_CommandReceivedToServer)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 ClientCallId = 1;</code>
   */
  long getClientCallId();
}
