// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_global.proto

package ir.ms.pb;

public interface PB_CommandReceivedToClientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_CommandReceivedToClient)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 ServerCallId = 1;</code>
   */
  long getServerCallId();
}
