// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_global.proto

package ir.ms.pb;

public interface PB_CommandToClientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_CommandToClient)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 ServerCallId = 1;</code>
   */
  long getServerCallId();

  /**
   * <code>string Command = 2;</code>
   */
  java.lang.String getCommand();
  /**
   * <code>string Command = 2;</code>
   */
  com.google.protobuf.ByteString
      getCommandBytes();

  /**
   * <code>bytes Data = 3;</code>
   */
  com.google.protobuf.ByteString getData();
}
