// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: global.proto

package ir.ms.pb;

public interface PB_PushMsgAddManyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_PushMsgAddMany)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .PB_Message Messages = 1;</code>
   */
  java.util.List<ir.ms.pb.PB_Message> 
      getMessagesList();
  /**
   * <code>repeated .PB_Message Messages = 1;</code>
   */
  ir.ms.pb.PB_Message getMessages(int index);
  /**
   * <code>repeated .PB_Message Messages = 1;</code>
   */
  int getMessagesCount();

  /**
   * <code>repeated .PB_UserWithMe Users = 2;</code>
   */
  java.util.List<ir.ms.pb.PB_UserWithMe> 
      getUsersList();
  /**
   * <code>repeated .PB_UserWithMe Users = 2;</code>
   */
  ir.ms.pb.PB_UserWithMe getUsers(int index);
  /**
   * <code>repeated .PB_UserWithMe Users = 2;</code>
   */
  int getUsersCount();
}
