// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: global.proto

package ir.ms.pb;

public interface PB_ResultMsgAddManyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_ResultMsgAddMany)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.PB_Response Response = 1;</code>
   */
  boolean hasResponse();
  /**
   * <code>.PB_Response Response = 1;</code>
   */
  ir.ms.pb.PB_Response getResponse();
}
