// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_rpc_user.proto

package ir.ms.pb;

public interface PB_UserResponseOffline_ChangePrivacyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PB_UserResponseOffline_ChangePrivacy)
    com.google.protobuf.MessageLiteOrBuilder {
}
