// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PB_seen_msgs.proto

package ir.ms.pb;

public final class PBSeenMsgs {
  private PBSeenMsgs() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
