// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_enums.proto

package ir.ms.pb;

/** Protobuf enum {@code ProfilePrivacyLevelEnum} */
public enum ProfilePrivacyLevelEnum implements com.google.protobuf.Internal.EnumLite {
  /** <code>NONE = 0;</code> */
  NONE(0),
  UNRECOGNIZED(-1),
  ;

  /** <code>NONE = 0;</code> */
  public static final int NONE_VALUE = 0;

  public final int getNumber() {
    return value;
  }

  /** @deprecated Use {@link #forNumber(int)} instead. */
  @java.lang.Deprecated
  public static ProfilePrivacyLevelEnum valueOf(int value) {
    return forNumber(value);
  }

  public static ProfilePrivacyLevelEnum forNumber(int value) {
    switch (value) {
      case 0:
        return NONE;
      default:
        return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ProfilePrivacyLevelEnum>
      internalGetValueMap() {
    return internalValueMap;
  }

  private static final com.google.protobuf.Internal.EnumLiteMap<ProfilePrivacyLevelEnum>
      internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProfilePrivacyLevelEnum>() {
            public ProfilePrivacyLevelEnum findValueByNumber(int number) {
              return ProfilePrivacyLevelEnum.forNumber(number);
            }
          };

  private final int value;

  private ProfilePrivacyLevelEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ProfilePrivacyLevelEnum)
}
