// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_enums.proto

package ir.ms.pb;

/**
 * Protobuf enum {@code RoomTypeEnum}
 */
public enum RoomTypeEnum
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>UNKNOWN_ROOM_TYPE = 0;</code>
   */
  UNKNOWN_ROOM_TYPE(0),
  /**
   * <code>DIRECT = 1;</code>
   */
  DIRECT(1),
  /**
   * <code>GROUP = 2;</code>
   */
  GROUP(2),
  /**
   * <code>CHANNEL = 3;</code>
   */
  CHANNEL(3),
  /**
   * <pre>
   *    BULK = 3;
   * </pre>
   *
   * <code>BROADCAST = 4;</code>
   */
  BROADCAST(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN_ROOM_TYPE = 0;</code>
   */
  public static final int UNKNOWN_ROOM_TYPE_VALUE = 0;
  /**
   * <code>DIRECT = 1;</code>
   */
  public static final int DIRECT_VALUE = 1;
  /**
   * <code>GROUP = 2;</code>
   */
  public static final int GROUP_VALUE = 2;
  /**
   * <code>CHANNEL = 3;</code>
   */
  public static final int CHANNEL_VALUE = 3;
  /**
   * <pre>
   *    BULK = 3;
   * </pre>
   *
   * <code>BROADCAST = 4;</code>
   */
  public static final int BROADCAST_VALUE = 4;


  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RoomTypeEnum valueOf(int value) {
    return forNumber(value);
  }

  public static RoomTypeEnum forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_ROOM_TYPE;
      case 1: return DIRECT;
      case 2: return GROUP;
      case 3: return CHANNEL;
      case 4: return BROADCAST;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RoomTypeEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RoomTypeEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RoomTypeEnum>() {
          public RoomTypeEnum findValueByNumber(int number) {
            return RoomTypeEnum.forNumber(number);
          }
        };

  private final int value;

  private RoomTypeEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:RoomTypeEnum)
}

