// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_enums.proto

package ir.ms.pb;

/**
 * Protobuf enum {@code RoomMultiPrivacyEnum}
 */
public enum RoomMultiPrivacyEnum
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>PRIVATE_ROOM = 0;</code>
   */
  PRIVATE_ROOM(0),
  /**
   * <code>PUBLIC_ROOM = 1;</code>
   */
  PUBLIC_ROOM(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PRIVATE_ROOM = 0;</code>
   */
  public static final int PRIVATE_ROOM_VALUE = 0;
  /**
   * <code>PUBLIC_ROOM = 1;</code>
   */
  public static final int PUBLIC_ROOM_VALUE = 1;


  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static RoomMultiPrivacyEnum valueOf(int value) {
    return forNumber(value);
  }

  public static RoomMultiPrivacyEnum forNumber(int value) {
    switch (value) {
      case 0: return PRIVATE_ROOM;
      case 1: return PUBLIC_ROOM;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<RoomMultiPrivacyEnum>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      RoomMultiPrivacyEnum> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<RoomMultiPrivacyEnum>() {
          public RoomMultiPrivacyEnum findValueByNumber(int number) {
            return RoomMultiPrivacyEnum.forNumber(number);
          }
        };

  private final int value;

  private RoomMultiPrivacyEnum(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:RoomMultiPrivacyEnum)
}

