// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_del.proto

package ir.ms.pb;

/** Protobuf type {@code PB_RequestMsgAddMany} */
public final class PB_RequestMsgAddMany
    extends com.google.protobuf.GeneratedMessageLite<
        PB_RequestMsgAddMany, PB_RequestMsgAddMany.Builder>
    implements
    // @@protoc_insertion_point(message_implements:PB_RequestMsgAddMany)
    PB_RequestMsgAddManyOrBuilder {
  private PB_RequestMsgAddMany() {
    messages_ = emptyProtobufList();
  }

  private int bitField0_;
  public static final int REQUEST_FIELD_NUMBER = 1;
  private ir.ms.pb.PB_Request request_;
  /** <code>.PB_Request Request = 1;</code> */
  public boolean hasRequest() {
    return request_ != null;
  }
  /** <code>.PB_Request Request = 1;</code> */
  public ir.ms.pb.PB_Request getRequest() {
    return request_ == null ? ir.ms.pb.PB_Request.getDefaultInstance() : request_;
  }
  /** <code>.PB_Request Request = 1;</code> */
  private void setRequest(ir.ms.pb.PB_Request value) {
    if (value == null) {
      throw new NullPointerException();
    }
    request_ = value;
  }
  /** <code>.PB_Request Request = 1;</code> */
  private void setRequest(ir.ms.pb.PB_Request.Builder builderForValue) {
    request_ = builderForValue.build();
  }
  /** <code>.PB_Request Request = 1;</code> */
  private void mergeRequest(ir.ms.pb.PB_Request value) {
    if (request_ != null && request_ != ir.ms.pb.PB_Request.getDefaultInstance()) {
      request_ = ir.ms.pb.PB_Request.newBuilder(request_).mergeFrom(value).buildPartial();
    } else {
      request_ = value;
    }
  }
  /** <code>.PB_Request Request = 1;</code> */
  private void clearRequest() {
    request_ = null;
  }

  public static final int MESSAGES_FIELD_NUMBER = 2;
  private com.google.protobuf.Internal.ProtobufList<ir.ms.pb.PB_Message> messages_;
  /**
   *
   *
   * <pre>
   * repeated PB_UserWithMe Users = 2;
   * </pre>
   *
   * <code>repeated .PB_Message Messages = 2;</code>
   */
  public java.util.List<ir.ms.pb.PB_Message> getMessagesList() {
    return messages_;
  }
  /**
   *
   *
   * <pre>
   * repeated PB_UserWithMe Users = 2;
   * </pre>
   *
   * <code>repeated .PB_Message Messages = 2;</code>
   */
  public java.util.List<? extends ir.ms.pb.PB_MessageOrBuilder> getMessagesOrBuilderList() {
    return messages_;
  }
  /**
   *
   *
   * <pre>
   * repeated PB_UserWithMe Users = 2;
   * </pre>
   *
   * <code>repeated .PB_Message Messages = 2;</code>
   */
  public int getMessagesCount() {
    return messages_.size();
  }
  /**
   *
   *
   * <pre>
   * repeated PB_UserWithMe Users = 2;
   * </pre>
   *
   * <code>repeated .PB_Message Messages = 2;</code>
   */
  public ir.ms.pb.PB_Message getMessages(int index) {
    return messages_.get(index);
  }
  /**
   *
   *
   * <pre>
   * repeated PB_UserWithMe Users = 2;
   * </pre>
   *
   * <code>repeated .PB_Message Messages = 2;</code>
   */
  public ir.ms.pb.PB_MessageOrBuilder getMessagesOrBuilder(int index) {
    return messages_.get(index);
  }

  private void ensureMessagesIsMutable() {
    if (!messages_.isModifiable()) {
      messages_ = com.google.protobuf.GeneratedMessageLite.mutableCopy(messages_);
    }
  }

  /**
   *
   *
   * <pre>
   * repeated PB_UserWithMe Users = 2;
   * </pre>
   *
   * <code>repeated .PB_Message Messages = 2;</code>
   */
  private void setMessages(int index, ir.ms.pb.PB_Message value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureMessagesIsMutable();
    messages_.set(index, value);
  }
  /**
   *
   *
   * <pre>
   * repeated PB_UserWithMe Users = 2;
   * </pre>
   *
   * <code>repeated .PB_Message Messages = 2;</code>
   */
  private void setMessages(int index, ir.ms.pb.PB_Message.Builder builderForValue) {
    ensureMessagesIsMutable();
    messages_.set(index, builderForValue.build());
  }
  /**
   *
   *
   * <pre>
   * repeated PB_UserWithMe Users = 2;
   * </pre>
   *
   * <code>repeated .PB_Message Messages = 2;</code>
   */
  private void addMessages(ir.ms.pb.PB_Message value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureMessagesIsMutable();
    messages_.add(value);
  }
  /**
   *
   *
   * <pre>
   * repeated PB_UserWithMe Users = 2;
   * </pre>
   *
   * <code>repeated .PB_Message Messages = 2;</code>
   */
  private void addMessages(int index, ir.ms.pb.PB_Message value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureMessagesIsMutable();
    messages_.add(index, value);
  }
  /**
   *
   *
   * <pre>
   * repeated PB_UserWithMe Users = 2;
   * </pre>
   *
   * <code>repeated .PB_Message Messages = 2;</code>
   */
  private void addMessages(ir.ms.pb.PB_Message.Builder builderForValue) {
    ensureMessagesIsMutable();
    messages_.add(builderForValue.build());
  }
  /**
   *
   *
   * <pre>
   * repeated PB_UserWithMe Users = 2;
   * </pre>
   *
   * <code>repeated .PB_Message Messages = 2;</code>
   */
  private void addMessages(int index, ir.ms.pb.PB_Message.Builder builderForValue) {
    ensureMessagesIsMutable();
    messages_.add(index, builderForValue.build());
  }
  /**
   *
   *
   * <pre>
   * repeated PB_UserWithMe Users = 2;
   * </pre>
   *
   * <code>repeated .PB_Message Messages = 2;</code>
   */
  private void addAllMessages(java.lang.Iterable<? extends ir.ms.pb.PB_Message> values) {
    ensureMessagesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(values, messages_);
  }
  /**
   *
   *
   * <pre>
   * repeated PB_UserWithMe Users = 2;
   * </pre>
   *
   * <code>repeated .PB_Message Messages = 2;</code>
   */
  private void clearMessages() {
    messages_ = emptyProtobufList();
  }
  /**
   *
   *
   * <pre>
   * repeated PB_UserWithMe Users = 2;
   * </pre>
   *
   * <code>repeated .PB_Message Messages = 2;</code>
   */
  private void removeMessages(int index) {
    ensureMessagesIsMutable();
    messages_.remove(index);
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
    if (request_ != null) {
      output.writeMessage(1, getRequest());
    }
    for (int i = 0; i < messages_.size(); i++) {
      output.writeMessage(2, messages_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (request_ != null) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, getRequest());
    }
    for (int i = 0; i < messages_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, messages_.get(i));
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static ir.ms.pb.PB_RequestMsgAddMany parseFrom(com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static ir.ms.pb.PB_RequestMsgAddMany parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static ir.ms.pb.PB_RequestMsgAddMany parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
  }

  public static ir.ms.pb.PB_RequestMsgAddMany parseFrom(
      byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }

  public static ir.ms.pb.PB_RequestMsgAddMany parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static ir.ms.pb.PB_RequestMsgAddMany parseFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static ir.ms.pb.PB_RequestMsgAddMany parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static ir.ms.pb.PB_RequestMsgAddMany parseDelimitedFrom(
      java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static ir.ms.pb.PB_RequestMsgAddMany parseFrom(com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
  }

  public static ir.ms.pb.PB_RequestMsgAddMany parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(ir.ms.pb.PB_RequestMsgAddMany prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /** Protobuf type {@code PB_RequestMsgAddMany} */
  public static final class Builder
      extends com.google.protobuf.GeneratedMessageLite.Builder<
          ir.ms.pb.PB_RequestMsgAddMany, Builder>
      implements
      // @@protoc_insertion_point(builder_implements:PB_RequestMsgAddMany)
      ir.ms.pb.PB_RequestMsgAddManyOrBuilder {
    // Construct using ir.ms.pb.PB_RequestMsgAddMany.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    /** <code>.PB_Request Request = 1;</code> */
    public boolean hasRequest() {
      return instance.hasRequest();
    }
    /** <code>.PB_Request Request = 1;</code> */
    public ir.ms.pb.PB_Request getRequest() {
      return instance.getRequest();
    }
    /** <code>.PB_Request Request = 1;</code> */
    public Builder setRequest(ir.ms.pb.PB_Request value) {
      copyOnWrite();
      instance.setRequest(value);
      return this;
    }
    /** <code>.PB_Request Request = 1;</code> */
    public Builder setRequest(ir.ms.pb.PB_Request.Builder builderForValue) {
      copyOnWrite();
      instance.setRequest(builderForValue);
      return this;
    }
    /** <code>.PB_Request Request = 1;</code> */
    public Builder mergeRequest(ir.ms.pb.PB_Request value) {
      copyOnWrite();
      instance.mergeRequest(value);
      return this;
    }
    /** <code>.PB_Request Request = 1;</code> */
    public Builder clearRequest() {
      copyOnWrite();
      instance.clearRequest();
      return this;
    }

    /**
     *
     *
     * <pre>
     * repeated PB_UserWithMe Users = 2;
     * </pre>
     *
     * <code>repeated .PB_Message Messages = 2;</code>
     */
    public java.util.List<ir.ms.pb.PB_Message> getMessagesList() {
      return java.util.Collections.unmodifiableList(instance.getMessagesList());
    }
    /**
     *
     *
     * <pre>
     * repeated PB_UserWithMe Users = 2;
     * </pre>
     *
     * <code>repeated .PB_Message Messages = 2;</code>
     */
    public int getMessagesCount() {
      return instance.getMessagesCount();
    }
    /**
     *
     *
     * <pre>
     * repeated PB_UserWithMe Users = 2;
     * </pre>
     *
     * <code>repeated .PB_Message Messages = 2;</code>
     */

    public ir.ms.pb.PB_Message getMessages(int index) {
      return instance.getMessages(index);
    }
    /**
     *
     *
     * <pre>
     * repeated PB_UserWithMe Users = 2;
     * </pre>
     *
     * <code>repeated .PB_Message Messages = 2;</code>
     */
    public Builder setMessages(int index, ir.ms.pb.PB_Message value) {
      copyOnWrite();
      instance.setMessages(index, value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * repeated PB_UserWithMe Users = 2;
     * </pre>
     *
     * <code>repeated .PB_Message Messages = 2;</code>
     */
    public Builder setMessages(int index, ir.ms.pb.PB_Message.Builder builderForValue) {
      copyOnWrite();
      instance.setMessages(index, builderForValue);
      return this;
    }
    /**
     *
     *
     * <pre>
     * repeated PB_UserWithMe Users = 2;
     * </pre>
     *
     * <code>repeated .PB_Message Messages = 2;</code>
     */
    public Builder addMessages(ir.ms.pb.PB_Message value) {
      copyOnWrite();
      instance.addMessages(value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * repeated PB_UserWithMe Users = 2;
     * </pre>
     *
     * <code>repeated .PB_Message Messages = 2;</code>
     */
    public Builder addMessages(int index, ir.ms.pb.PB_Message value) {
      copyOnWrite();
      instance.addMessages(index, value);
      return this;
    }
    /**
     *
     *
     * <pre>
     * repeated PB_UserWithMe Users = 2;
     * </pre>
     *
     * <code>repeated .PB_Message Messages = 2;</code>
     */
    public Builder addMessages(ir.ms.pb.PB_Message.Builder builderForValue) {
      copyOnWrite();
      instance.addMessages(builderForValue);
      return this;
    }
    /**
     *
     *
     * <pre>
     * repeated PB_UserWithMe Users = 2;
     * </pre>
     *
     * <code>repeated .PB_Message Messages = 2;</code>
     */
    public Builder addMessages(int index, ir.ms.pb.PB_Message.Builder builderForValue) {
      copyOnWrite();
      instance.addMessages(index, builderForValue);
      return this;
    }
    /**
     *
     *
     * <pre>
     * repeated PB_UserWithMe Users = 2;
     * </pre>
     *
     * <code>repeated .PB_Message Messages = 2;</code>
     */
    public Builder addAllMessages(java.lang.Iterable<? extends ir.ms.pb.PB_Message> values) {
      copyOnWrite();
      instance.addAllMessages(values);
      return this;
    }
    /**
     *
     *
     * <pre>
     * repeated PB_UserWithMe Users = 2;
     * </pre>
     *
     * <code>repeated .PB_Message Messages = 2;</code>
     */
    public Builder clearMessages() {
      copyOnWrite();
      instance.clearMessages();
      return this;
    }
    /**
     *
     *
     * <pre>
     * repeated PB_UserWithMe Users = 2;
     * </pre>
     *
     * <code>repeated .PB_Message Messages = 2;</code>
     */
    public Builder removeMessages(int index) {
      copyOnWrite();
      instance.removeMessages(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:PB_RequestMsgAddMany)
  }

  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method, Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE:
        {
          return new ir.ms.pb.PB_RequestMsgAddMany();
        }
      case IS_INITIALIZED:
        {
          return DEFAULT_INSTANCE;
        }
      case MAKE_IMMUTABLE:
        {
          messages_.makeImmutable();
          return null;
        }
      case NEW_BUILDER:
        {
          return new Builder();
        }
      case VISIT:
        {
          Visitor visitor = (Visitor) arg0;
          ir.ms.pb.PB_RequestMsgAddMany other = (ir.ms.pb.PB_RequestMsgAddMany) arg1;
          request_ = visitor.visitMessage(request_, other.request_);
          messages_ = visitor.visitList(messages_, other.messages_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor.INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
      case MERGE_FROM_STREAM:
        {
          com.google.protobuf.CodedInputStream input = (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default:
                  {
                    if (!input.skipField(tag)) {
                      done = true;
                    }
                    break;
                  }
                case 10:
                  {
                    ir.ms.pb.PB_Request.Builder subBuilder = null;
                    if (request_ != null) {
                      subBuilder = request_.toBuilder();
                    }
                    request_ = input.readMessage(ir.ms.pb.PB_Request.parser(), extensionRegistry);
                    if (subBuilder != null) {
                      subBuilder.mergeFrom(request_);
                      request_ = subBuilder.buildPartial();
                    }

                    break;
                  }
                case 18:
                  {
                    if (!messages_.isModifiable()) {
                      messages_ = com.google.protobuf.GeneratedMessageLite.mutableCopy(messages_);
                    }
                    messages_.add(
                        input.readMessage(ir.ms.pb.PB_Message.parser(), extensionRegistry));
                    break;
                  }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(e.getMessage())
                    .setUnfinishedMessage(this));
          } finally {
          }
        }
      case GET_DEFAULT_INSTANCE:
        {
          return DEFAULT_INSTANCE;
        }
      case GET_PARSER:
        {
          if (PARSER == null) {
            synchronized (ir.ms.pb.PB_RequestMsgAddMany.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
    }
    throw new UnsupportedOperationException();
  }

  // @@protoc_insertion_point(class_scope:PB_RequestMsgAddMany)
  private static final ir.ms.pb.PB_RequestMsgAddMany DEFAULT_INSTANCE;

  static {
    DEFAULT_INSTANCE = new PB_RequestMsgAddMany();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static ir.ms.pb.PB_RequestMsgAddMany getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PB_RequestMsgAddMany> PARSER;

  public static com.google.protobuf.Parser<PB_RequestMsgAddMany> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}
