// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_rpc_user.proto

package ir.ms.pb;

public interface PB_UserOfflineResponse_UnBlockUserOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:PB_UserOfflineResponse_UnBlockUser)
    com.google.protobuf.MessageLiteOrBuilder {

  /** <code>repeated .UserView Users = 1;</code> */
  java.util.List<ir.ms.pb.UserView> getUsersList();
  /** <code>repeated .UserView Users = 1;</code> */
  ir.ms.pb.UserView getUsers(int index);
  /** <code>repeated .UserView Users = 1;</code> */
  int getUsersCount();
}
