// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb_rpc_user.proto

package ir.ms.pb;

public interface PB_UserParam_BlockUserOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:PB_UserParam_BlockUser)
    com.google.protobuf.MessageLiteOrBuilder {

  /** <code>int32 UserId = 1;</code> */
  int getUserId();

  /** <code>string UserName = 2;</code> */
  java.lang.String getUserName();
  /** <code>string UserName = 2;</code> */
  com.google.protobuf.ByteString getUserNameBytes();
}
